import { Observation, IdeaCard, MVE, ResearchArea, Paper, LEGACY_STATUS_MAP } from './types';

export const mockResearchAreas: ResearchArea[] = [
  {
    id: 'area-perception',
    name: 'Robot Perception｜机器人感知',
    description: '机器人感知系统研究，包括视觉、激光、触觉等多模态感知',
    category: '感知',
    keywords: ['robot perception', 'sensing', 'multi-modal'],
    focusQuestions: ['如何提升感知鲁棒性？', '多传感器如何有效融合？'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-02T00:00:00Z',
  },
  {
    id: 'area-state-estimation',
    name: 'State Estimation｜状态估计',
    description: '机器人状态估计理论与方法，包括滤波、优化、传感器融合',
    category: '感知',
    keywords: ['state estimation', 'Kalman filter', 'optimization', 'sensor fusion'],
    focusQuestions: [
      '如何在传感器故障时保持估计稳定性？',
      '多传感器融合的最优架构是什么？',
      '如何处理动态环境下的状态估计？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-02T10:00:00Z',
  },
  {
    id: 'area-slam',
    name: 'SLAM｜同步定位与建图',
    description: '同时定位与地图构建，包括视觉SLAM、激光SLAM、多传感器SLAM',
    category: '感知',
    keywords: ['SLAM', 'localization', 'mapping', 'pose estimation'],
    focusQuestions: [
      '动态环境下SLAM如何保持鲁棒？',
      '如何实现长期自主导航的SLAM？',
      '语义信息如何提升SLAM性能？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-03T00:00:00Z',
  },
  {
    id: 'area-vslam',
    name: 'Visual SLAM｜视觉 SLAM',
    description: '基于视觉的SLAM方法，包括单目、双目、RGBD等',
    category: '感知',
    keywords: ['visual SLAM', 'monocular', 'stereo', 'RGBD', 'ORB'],
    focusQuestions: ['特征点法vs直接法的权衡', '弱纹理环境下的视觉SLAM'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-28T00:00:00Z',
  },
  {
    id: 'area-vio',
    name: 'VIO｜视觉惯性里程计',
    description: '视觉与IMU融合的里程计算法，包括紧耦合、松耦合方案',
    category: '感知',
    keywords: ['VIO', 'visual-inertial', 'IMU', 'odometry', '紧耦合'],
    focusQuestions: [
      'IMU预积分的精度边界在哪里？',
      '如何处理IMU零偏的在线估计？',
      '视觉故障时VIO如何退化？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
  },
  {
    id: 'area-msf',
    name: 'Multi-Sensor Fusion｜多传感器融合',
    description: '多传感器融合理论与方法，包括卡尔曼滤波、因子图、优化方法',
    category: '感知',
    keywords: ['sensor fusion', 'Kalman filter', 'factor graph', 'optimization'],
    focusQuestions: [
      '异构传感器的时间同步如何处理？',
      '传感器故障检测与隔离策略？',
      '融合架构的最优设计原则？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-30T00:00:00Z',
  },
  {
    id: 'area-3d-perception',
    name: '3D Perception｜三维感知',
    description: '三维环境感知，包括3D检测、3D分割、点云处理',
    category: '感知',
    keywords: ['3D detection', 'point cloud', 'LiDAR', '3D segmentation'],
    focusQuestions: ['点云与图像的融合策略', '小目标3D检测的挑战'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-25T00:00:00Z',
  },
  {
    id: 'area-dynamic-scene',
    name: 'Dynamic Scene Understanding｜动态场景理解',
    description: '动态场景的感知与理解，包括运动目标检测、跟踪、预测',
    category: '感知',
    keywords: ['dynamic scene', 'motion detection', 'tracking', 'prediction'],
    focusQuestions: ['动态目标如何影响SLAM？', '运动预测的不确定性建模'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-20T00:00:00Z',
  },
  {
    id: 'area-semantic-mapping',
    name: 'Semantic Mapping｜语义建图',
    description: '语义信息与地图构建的结合，包括语义SLAM、动态语义地图',
    category: '感知',
    keywords: ['semantic mapping', 'semantic SLAM', 'dynamic map'],
    focusQuestions: ['语义信息如何提升导航？', '动态语义地图的更新策略'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-18T00:00:00Z',
  },
  {
    id: 'area-robot-learning',
    name: 'Robot Learning｜机器人学习',
    description: '机器学习在机器人中的应用，包括强化学习、模仿学习等',
    category: '学习',
    keywords: ['robot learning', 'RL', 'imitation learning'],
    focusQuestions: ['Sim-to-Real如何跨越？', '样本效率如何提升？'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-22T00:00:00Z',
  },
  {
    id: 'area-imitation',
    name: 'Imitation Learning｜模仿学习',
    description: '模仿学习方法，包括行为克隆、逆强化学习等',
    category: '学习',
    keywords: ['imitation learning', 'behavior cloning', 'IRL'],
    focusQuestions: ['分布偏移问题如何解决？', '专家数据质量的影响'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-23T00:00:00Z',
  },
  {
    id: 'area-diffusion-policy',
    name: 'Diffusion Policy｜扩散策略',
    description: '扩散模型在机器人策略学习中的应用',
    category: '学习',
    keywords: ['diffusion model', 'policy learning', 'robot manipulation'],
    focusQuestions: [
      '扩散策略的推理速度能否满足实时控制？',
      '扩散策略相比BC/GMM有何本质优势？',
      '如何用扩散建模多模态动作分布？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-02T15:00:00Z',
  },
  {
    id: 'area-vla',
    name: 'VLA｜Vision-Language-Action Models',
    description: '视觉-语言-动作模型，端到端机器人控制大模型',
    category: '前沿',
    keywords: ['VLA', 'vision-language-action', 'robot foundation model', 'RT-2'],
    focusQuestions: [
      'VLA能否泛化到未见任务？',
      '如何用低成本数据训练VLA？',
      'VLA的实时推理如何加速？',
      'VLA与传统控制的边界在哪里？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-03T09:00:00Z',
  },
  {
    id: 'area-world-models',
    name: 'World Models｜世界模型',
    description: '世界模型与基于模型的强化学习，用于机器人规划与控制',
    category: '前沿',
    keywords: ['world model', 'model-based RL', 'planning', 'latent dynamics'],
    focusQuestions: [
      '世界模型能否支撑长程规划？',
      '如何学习可组合的世界模型？',
      '世界模型的不确定性如何量化？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-01T14:00:00Z',
  },
  {
    id: 'area-embodied-ai',
    name: 'Embodied AI｜具身智能',
    description: '具身智能研究，包括导航、操作、交互等',
    category: '前沿',
    keywords: ['embodied AI', 'navigation', 'manipulation', 'interaction'],
    focusQuestions: ['具身智能的评估体系？', '通用具身智能的路径？'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-29T00:00:00Z',
  },
  {
    id: 'area-foundation',
    name: 'Robotics Foundation Models｜机器人基础模型',
    description: '机器人领域的基础模型研究，包括预训练、微调、对齐',
    category: '前沿',
    keywords: ['foundation model', 'pre-training', 'fine-tuning', 'alignment'],
    focusQuestions: ['机器人预训练数据如何获取？', '基础模型如何适配具体任务？'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-27T00:00:00Z',
  },
  {
    id: 'area-dexterous',
    name: 'Dexterous Manipulation｜灵巧操作',
    description: '机器人灵巧操作，包括多指手、抓取、操作规划',
    category: '控制',
    keywords: ['dexterous manipulation', 'grasping', 'multi-finger hand'],
    focusQuestions: ['多指手的接触力控制？', '未知物体的抓取策略？'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-21T00:00:00Z',
  },
  {
    id: 'area-sim2real',
    name: 'Sim-to-Real｜仿真到现实迁移',
    description: '仿真到现实的迁移方法，包括域随机化、域适应等',
    category: '学习',
    keywords: ['sim-to-real', 'domain randomization', 'domain adaptation', 'simulation'],
    focusQuestions: ['仿真器的真实性边界？', 'Sim-to-Real的系统性方法论？'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-24T00:00:00Z',
  },
];

export const mockPapers: Paper[] = [
  {
    id: 'paper-vla-001',
    title: 'RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control',
    authors: 'Anthony Brohan, Noah Brown, Justice Carbajal, et al.',
    year: 2023,
    venue: 'CoRL',
    arxivUrl: 'https://arxiv.org/abs/2307.15818',
    pdfUrl: 'https://arxiv.org/pdf/2307.15818',
    htmlUrl: '',
    feishuNoteUrl: 'https://feishu.cn/docx/xxx-rt2-notes',
    codeUrl: '',
    areaIds: ['area-vla', 'area-foundation'],
    readingStatus: 'deep_reading',
    methodKeywords: ['VLA', 'vision-language', 'robot control', 'RT-2'],
    oneSentenceSummary: '将视觉-语言模型直接输出动作，实现端到端机器人控制，展示了web知识向机器人操作的迁移潜力。',
    problem: '传统机器人策略学习需要大量机器人数据，难以泛化到未见任务和环境。',
    coreContribution: '提出RT-2，一种视觉-语言-动作模型，将视觉语言模型的输出直接映射为机器人动作token，实现从web知识到机器人控制的迁移。',
    methodSketch: '1) 使用机器人数据微调视觉语言模型；2) 将动作序列编码为token；3) 模型直接输出动作token序列；4) 通过自回归解码生成完整动作。',
    evidence: {
      tasks: ['Pick-and-place', 'Object sorting', 'Navigation', 'Door opening'],
      baselines: ['RT-1', 'BC (Behavior Cloning)', 'Gato'],
      metrics: ['Task success rate', 'Generalization to unseen objects'],
      keyResults: ['在1000+ unseen objects上成功率提升3x', '端到端推理无需中间规划', 'web知识迁移到机器人控制'],
    },
    assumptions: ['大量机器人数据可用', '动作空间可以离散化为token', '视觉语言模型知识可以迁移到机器人动作'],
    limitations: ['推理速度慢（~3s/step）', '未见任务泛化能力有限', '需要大量机器人数据训练'],
    relevanceToMyResearch: '核心关注方向，VLA是机器人基础模型的重要路径，需要持续跟踪。',
    questionsToVerify: ['RT-2的泛化能力在真实复杂场景下如何？', '推理速度能否满足实时控制要求？', '动作token化对连续控制的精度损失有多大？'],
    limitationsOrQuestions: '推理速度太慢（~3s/step），无法实时控制；未见任务泛化能力有限；需要大量机器人数据。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: ['idea-vla-speedup'],
    createdAt: '2026-06-15T10:00:00Z',
    updatedAt: '2026-07-02T14:00:00Z',
  },
  {
    id: 'paper-vla-002',
    title: 'OpenVLA: An Open-Source Vision-Language-Action Model',
    authors: 'Deepak Pathak, et al.',
    year: 2024,
    venue: 'arXiv',
    arxivUrl: 'https://arxiv.org/abs/2406.09246',
    pdfUrl: 'https://arxiv.org/pdf/2406.09246',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: 'https://github.com/openvla/openvla',
    areaIds: ['area-vla', 'area-foundation'],
    readingStatus: 'skimmed',
    methodKeywords: ['VLA', 'open-source', 'robot foundation model'],
    oneSentenceSummary: '开源的VLA模型，提供了训练代码和模型权重，降低了VLA研究门槛。',
    problem: '现有VLA模型多为闭源，限制了学术研究和社区贡献。',
    coreContribution: '开源了完整的VLA训练框架和预训练模型，支持多种机器人平台和任务。',
    methodSketch: '1) 基于Mamba架构设计VLA模型；2) 使用多模态数据集预训练；3) 提供训练和推理代码；4) 支持零样本迁移到新任务。',
    evidence: {
      tasks: ['Manipulation', 'Navigation', 'Mobile manipulation'],
      baselines: ['RT-2', 'RT-X'],
      metrics: ['Zero-shot success rate', 'Fine-tuning efficiency'],
      keyResults: ['零样本性能接近闭源模型', '训练效率提升2x', '支持多种机器人平台'],
    },
    assumptions: ['开源模型可以复现闭源性能', '社区可以基于开源框架继续改进'],
    limitations: ['训练数据量和多样性如何？', '性能与闭源模型差距多大？'],
    relevanceToMyResearch: '可以作为基线和实验平台，快速验证想法。',
    questionsToVerify: ['训练数据量和多样性如何？', '性能与闭源模型差距多大？', '是否支持自定义机器人平台？'],
    limitationsOrQuestions: '训练数据量和多样性如何？性能与闭源模型差距多大？',
    judgementLevel: 'useful',
    inspiredIdeaIds: [],
    createdAt: '2026-06-20T09:00:00Z',
    updatedAt: '2026-06-28T11:00:00Z',
  },
  {
    id: 'paper-wm-001',
    title: 'DreamerV3: Mastering Diverse Domains through World Models',
    authors: 'Danijar Hafner, Jurgis Pasukonis, Jimmy Ba, Timothy Lillicrap',
    year: 2023,
    venue: 'ICLR',
    arxivUrl: 'https://arxiv.org/abs/2301.04104',
    pdfUrl: 'https://arxiv.org/pdf/2301.04104',
    htmlUrl: '',
    feishuNoteUrl: 'https://feishu.cn/docx/xxx-dreamerv3',
    codeUrl: 'https://github.com/danijar/dreamerv3',
    areaIds: ['area-world-models', 'area-robot-learning'],
    readingStatus: 'reviewed',
    methodKeywords: ['world model', 'Dreamer', 'model-based RL', 'reinforcement learning'],
    oneSentenceSummary: '统一的世界模型强化学习算法，在多种任务上实现无超参数调优的SOTA性能。',
    problem: '现有的强化学习算法需要针对不同任务调优超参数，通用性差。',
    coreContribution: '提出DreamerV3，一种统一的世界模型RL算法，无需超参数调优即可在多种领域达到SOTA。',
    methodSketch: '1) 学习隐式世界模型；2) 在模型中规划；3) 端到端训练；4) 统一架构适配多种任务。',
    evidence: {
      tasks: ['Atari', 'MuJoCo', 'DM Control', 'Robotics'],
      baselines: ['DreamerV2', 'SAC', 'PPO'],
      metrics: ['Average reward', 'Sample efficiency', 'Wall-clock time'],
      keyResults: ['无需调参在所有任务达到SOTA', '样本效率提升10x', '训练时间大幅缩短'],
    },
    assumptions: ['世界模型可以准确建模环境动态', '规划在模型中有效', '统一架构适用于所有任务'],
    limitations: ['像素级世界模型在复杂3D环境效率问题', '长时间预测准确性下降'],
    relevanceToMyResearch: '世界模型是机器人规划的基础，Dreamer系列是重要参考。',
    questionsToVerify: ['在真实机器人环境中表现如何？', '长时间预测的准确性如何？', '模型大小与性能的权衡？'],
    limitationsOrQuestions: '像素级世界模型在复杂3D环境的效率问题；长时间预测的准确性下降。',
    judgementLevel: 'idea_source',
    inspiredIdeaIds: [],
    createdAt: '2026-06-10T08:00:00Z',
    updatedAt: '2026-06-25T16:00:00Z',
  },
  {
    id: 'paper-slam-001',
    title: 'ORB-SLAM3: An Accurate Open-Source Library for Visual, Visual-Inertial and Multi-Map SLAM',
    authors: 'Carlos Campos, Richard Elvira, Juan J. Gómez Rodríguez, et al.',
    year: 2021,
    venue: 'TRO',
    arxivUrl: 'https://arxiv.org/abs/2007.11898',
    pdfUrl: 'https://arxiv.org/pdf/2007.11898',
    htmlUrl: '',
    feishuNoteUrl: 'https://feishu.cn/docx/xxx-orbslam3',
    codeUrl: 'https://github.com/UZ-SLAMLab/ORB_SLAM3',
    areaIds: ['area-slam', 'area-vslam', 'area-vio'],
    readingStatus: 'deep_reading',
    methodKeywords: ['ORB-SLAM', 'visual SLAM', 'VIO', 'multi-map'],
    oneSentenceSummary: '成熟的特征点法视觉/视觉惯性SLAM系统，支持多地图、IMU紧耦合，是VIO基线参考。',
    problem: '现有SLAM系统难以同时支持纯视觉、视觉惯性和多地图场景。',
    coreContribution: '提出ORB-SLAM3，统一支持纯视觉、视觉惯性和多地图SLAM，在多种数据集上达到SOTA。',
    methodSketch: '1) 特征提取与匹配；2) IMU预积分；3) 紧耦合优化；4) 多地图管理；5) 回环检测。',
    evidence: {
      tasks: ['Monocular SLAM', 'Stereo SLAM', 'Visual-Inertial SLAM', 'Multi-map'],
      baselines: ['ORB-SLAM2', 'VINS-Mono', 'OKVIS'],
      metrics: ['ATE', 'RPE', 'Robustness'],
      keyResults: ['TUM RGB-D上ATE提升20%', 'EuRoC上VIO性能领先', '多地图功能支持长时定位'],
    },
    assumptions: ['环境中存在足够的特征点', 'IMU参数已知', '环境基本静态'],
    limitations: ['弱纹理环境下特征点不足', '动态物体影响大', '回环检测依赖词袋模型'],
    relevanceToMyResearch: 'VIO方向的经典工作，需要深入理解其IMU预积分和优化框架。',
    questionsToVerify: ['在动态环境中的鲁棒性如何？', 'IMU零偏在线估计的精度？', '多地图切换的延迟？'],
    limitationsOrQuestions: '弱纹理环境下特征点不足；动态物体影响大；回环检测依赖词袋模型。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: ['idea-vio-dynamic'],
    createdAt: '2026-05-20T10:00:00Z',
    updatedAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'paper-vio-001',
    title: 'VINS-Mono: A Robust and Versatile Monocular Visual-Inertial State Estimator',
    authors: 'Tong Qin, Peiliang Li, Shaojie Shen',
    year: 2018,
    venue: 'TRO',
    arxivUrl: 'https://arxiv.org/abs/1708.03852',
    pdfUrl: 'https://arxiv.org/pdf/1708.03852',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: 'https://github.com/HKUST-Aerial-Robotics/VINS-Mono',
    areaIds: ['area-vio', 'area-state-estimation'],
    readingStatus: 'reviewed',
    methodKeywords: ['VIO', 'VINS-Mono', 'optimization', 'sliding window'],
    oneSentenceSummary: '基于滑动窗口优化的单目VIO经典工作，包含初始化、外参标定、回环检测完整模块。',
    problem: '单目视觉无法估计尺度，纯视觉SLAM在快速运动时容易丢失。',
    coreContribution: '提出VINS-Mono，基于滑动窗口优化的单目VIO，包含完整的初始化和优化框架。',
    methodSketch: '1) IMU预积分；2) 滑动窗口优化；3) 初始化（视觉+IMU）；4) 外参标定；5) 回环检测。',
    evidence: {
      tasks: ['Monocular visual-inertial odometry', 'Drone navigation'],
      baselines: ['MSCKF', 'OKVIS', 'SVO'],
      metrics: ['ATE', 'Computation time', 'Robustness'],
      keyResults: ['EuRoC数据集上SOTA', '计算效率高（~30ms/frame）', '初始化可靠'],
    },
    assumptions: ['IMU和相机时间同步准确', 'IMU噪声模型已知', '外参已知或可标定'],
    limitations: ['计算量较大', '对初始化质量敏感', '动态场景下鲁棒性不足'],
    relevanceToMyResearch: 'VIO方向的必读经典，优化框架的重要参考。',
    questionsToVerify: ['初始化失败率如何？', '长时间运行的漂移特性？', '在真实无人机上的表现？'],
    limitationsOrQuestions: '计算量较大；对初始化质量敏感；动态场景下鲁棒性不足。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: [],
    createdAt: '2026-05-15T09:00:00Z',
    updatedAt: '2026-06-20T14:00:00Z',
  },
  {
    id: 'paper-msf-001',
    title: 'FAST-LIO2: Fast Direct LiDAR-Inertial Odometry',
    authors: 'Wei Xu, Yixi Cai, Dongjiao He, Jiarong Lin, Fu Zhang',
    year: 2022,
    venue: 'TRO',
    arxivUrl: 'https://arxiv.org/abs/2107.06829',
    pdfUrl: 'https://arxiv.org/pdf/2107.06829',
    htmlUrl: '',
    feishuNoteUrl: 'https://feishu.cn/docx/xxx-fastlio2',
    codeUrl: 'https://github.com/hku-mars/FAST_LIO',
    areaIds: ['area-msf', 'area-slam', 'area-state-estimation'],
    readingStatus: 'deep_reading',
    methodKeywords: ['LiDAR SLAM', 'LIO', 'ikd-tree', 'incremental mapping'],
    oneSentenceSummary: '基于ikd-tree的紧耦合激光惯性里程计，实现了高效率、高精度的建图与定位。',
    problem: '传统LiDAR SLAM在大规模场景下效率低，难以实时运行。',
    coreContribution: '提出FAST-LIO2，基于ikd-tree增量kd树的数据结构，实现高速激光惯性里程计。',
    methodSketch: '1) ikd-tree增量建图；2) LiDAR点云去畸变；3) IMU预积分；4) 紧耦合优化；5) 实时里程计输出。',
    evidence: {
      tasks: ['LiDAR-inertial odometry', '3D mapping', 'Drone navigation'],
      baselines: ['FAST-LIO', 'LIO-SAM', 'LOAM'],
      metrics: ['ATE', 'FPS', 'Map size'],
      keyResults: ['实时运行>100Hz', '大规模场景下精度保持', 'ikd-tree效率提升10x'],
    },
    assumptions: ['高频率IMU可用', 'LiDAR数据质量良好', '运动连续'],
    limitations: ['依赖高频率IMU', '对运动畸变敏感', '回环检测需额外模块'],
    relevanceToMyResearch: '多传感器融合方向的重要工作，ikd-tree数据结构有参考价值。',
    questionsToVerify: ['在低速运动场景下的精度？', 'ikd-tree的内存占用？', '与其他传感器融合的接口？'],
    limitationsOrQuestions: '依赖高频率IMU；对运动畸变敏感；回环检测需额外模块。',
    judgementLevel: 'useful',
    inspiredIdeaIds: [],
    createdAt: '2026-06-05T08:00:00Z',
    updatedAt: '2026-06-30T09:00:00Z',
  },
  {
    id: 'paper-diffusion-001',
    title: 'Diffusion Policy: Visuomotor Policy Learning via Action Diffusion',
    authors: 'Cheng Chi, Siyuan Feng, Yilun Du, et al.',
    year: 2023,
    venue: 'RSS',
    arxivUrl: 'https://arxiv.org/abs/2303.04137',
    pdfUrl: 'https://arxiv.org/pdf/2303.04137',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: 'https://github.com/columbia-ai-robotics/diffusion_policy',
    areaIds: ['area-diffusion-policy', 'area-robot-learning'],
    readingStatus: 'skimmed',
    methodKeywords: ['diffusion model', 'policy learning', 'visuomotor', 'manipulation'],
    oneSentenceSummary: '用扩散模型生成动作序列，在多模态动作分布建模上优于GMM和BC。',
    problem: '传统策略学习方法难以建模多模态动作分布，在复杂操作任务中表现受限。',
    coreContribution: '提出Diffusion Policy，用扩散模型学习动作条件分布，在多模态动作任务上显著优于BC和GMM。',
    methodSketch: '1) 动作序列编码；2) 扩散过程建模；3) 条件采样生成动作；4) 去噪训练。',
    evidence: {
      tasks: ['PushT', 'Kitchen', 'Robotics manipulation'],
      baselines: ['BC', 'GMM', 'IL'],
      metrics: ['Task success rate', 'Action diversity', 'Sample efficiency'],
      keyResults: ['多模态任务成功率提升30%', '动作分布更多样', '样本效率高'],
    },
    assumptions: ['扩散模型可以准确建模动作分布', '足够的训练数据', '动作空间适合扩散建模'],
    limitations: ['推理速度慢，难以满足实时控制要求', '扩散步数与性能的权衡'],
    relevanceToMyResearch: '扩散策略是机器人学习的新兴方向，值得关注。',
    questionsToVerify: ['推理速度能否优化？', '在真实机器人上的表现？', '与其他策略学习方法的结合？'],
    limitationsOrQuestions: '推理速度慢，难以满足实时控制要求；扩散步数与性能的权衡。',
    judgementLevel: 'idea_source',
    inspiredIdeaIds: ['idea-diffusion-fast'],
    createdAt: '2026-06-22T10:00:00Z',
    updatedAt: '2026-07-02T16:00:00Z',
  },
  {
    id: 'paper-se-001',
    title: 'Quaternion Kinematics for the Error-State Kalman Filter',
    authors: 'Joan Solà',
    year: 2017,
    venue: 'arXiv',
    arxivUrl: 'https://arxiv.org/abs/1110.2165',
    pdfUrl: 'https://arxiv.org/pdf/1110.2165',
    htmlUrl: '',
    feishuNoteUrl: 'https://feishu.cn/docx/xxx-quat-ekf',
    codeUrl: '',
    areaIds: ['area-state-estimation'],
    readingStatus: 'reviewed',
    methodKeywords: ['Kalman filter', 'quaternion', 'error state', 'ESKF'],
    oneSentenceSummary: '误差状态卡尔曼滤波器的四元数运动学推导，是状态估计的理论基础。',
    problem: '传统卡尔曼滤波器在处理旋转时存在奇异值问题，误差表示困难。',
    coreContribution: '系统推导了基于误差状态的卡尔曼滤波器，使用四元数表示旋转，避免了奇异值问题。',
    methodSketch: '1) 误差状态定义；2) 四元数运动学建模；3) 状态预测；4) 状态更新；5) 全局状态恢复。',
    evidence: {
      tasks: ['State estimation', 'Attitude estimation', 'Navigation'],
      baselines: ['Standard EKF', 'UKF'],
      metrics: ['Accuracy', 'Numerical stability', 'Computational efficiency'],
      keyResults: ['避免万向锁问题', '数值稳定性好', '计算效率高'],
    },
    assumptions: ['误差足够小（小角度假设）', '过程噪声和观测噪声高斯分布', '系统模型准确'],
    limitations: ['理论性强，需要结合实践理解', '未涉及传感器融合细节'],
    relevanceToMyResearch: '状态估计的理论基础，必须掌握的经典工作。',
    questionsToVerify: ['在大误差场景下的表现？', '与其他状态表示方法的对比？', '实际实现中的数值稳定性？'],
    limitationsOrQuestions: '理论性强，需要结合实践理解；未涉及传感器融合细节。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: [],
    createdAt: '2026-05-10T08:00:00Z',
    updatedAt: '2026-06-15T12:00:00Z',
  },
  {
    id: 'paper-vslam-001',
    title: 'ORB-SLAM3: An Accurate Open-Source Library for Visual, Visual-Inertial and Multi-Map SLAM',
    authors: 'Carlos Campos, Richard Elvira, Juan J. Gómez, José M. M. Montiel, Juan D. Tardós',
    year: 2021,
    venue: 'TRO',
    arxivUrl: 'https://arxiv.org/abs/2007.11898',
    pdfUrl: 'https://arxiv.org/pdf/2007.11898',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: 'https://github.com/UZ-SLAMLab/ORB_SLAM3',
    areaIds: ['area-vslam', 'area-slam', 'area-vio'],
    readingStatus: 'reviewed',
    methodKeywords: ['ORB-SLAM', 'visual SLAM', 'VIO', 'multi-map', 'loop closure'],
    oneSentenceSummary: '经典的视觉/视觉惯性SLAM开源库，支持多地图和多种传感器配置，是视觉SLAM的标杆工作。',
    problem: '视觉SLAM系统在动态环境、快速运动下容易丢失，且缺乏对多地图、多传感器的统一支持。',
    coreContribution: '提出ORB-SLAM3，首个支持单目、双目、RGB-D、IMU等多种配置，支持多地图拼接的开源SLAM系统。',
    methodSketch: '1) 基于ORB特征的特征点法SLAM；2) 视觉惯性紧耦合优化；3) 多地图系统与回环检测；4) 自动地图保存与加载。',
    evidence: {
      tasks: ['EuRoC', 'TUM VI', 'KITTI', '自采数据集'],
      baselines: ['ORB-SLAM2', 'VINS-Mono', 'OKVIS'],
      metrics: ['ATE RMSE', '定位成功率', '运行效率'],
      keyResults: ['EuRoC上精度优于VINS-Mono', '支持多种传感器配置', '多地图系统提升鲁棒性'],
    },
    assumptions: ['环境中有足够的纹理特征', '光照条件相对稳定', '静态场景假设为主'],
    limitations: ['纯特征点法，低纹理场景表现差', '动态场景下鲁棒性不足', '依赖回环检测纠正漂移'],
    relevanceToMyResearch: '视觉SLAM的经典标杆工作，是理解SLAM系统设计的必读论文。',
    questionsToVerify: ['与深度学习方法的对比如何？', '动态场景下的鲁棒性改进空间？', '多地图系统的实际效果？'],
    limitationsOrQuestions: '纯特征点法，低纹理场景表现差；动态场景下鲁棒性不足。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: [],
    createdAt: '2026-04-20T10:00:00Z',
    updatedAt: '2026-06-10T15:00:00Z',
  },
  {
    id: 'paper-perception-001',
    title: 'Deep Residual Learning for Image Recognition',
    authors: 'Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun',
    year: 2016,
    venue: 'CVPR',
    arxivUrl: 'https://arxiv.org/abs/1512.03385',
    pdfUrl: 'https://arxiv.org/pdf/1512.03385',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: '',
    areaIds: ['area-perception', 'area-3d-perception'],
    readingStatus: 'reviewed',
    methodKeywords: ['ResNet', 'deep learning', 'image recognition', 'residual connection'],
    oneSentenceSummary: '提出残差连接解决深层网络退化问题，是深度学习的里程碑工作，ResNet成为机器人感知的基础骨干网络。',
    problem: '深层神经网络存在退化问题——网络越深，训练误差反而越大，限制了模型容量。',
    coreContribution: '提出残差学习框架，通过shortcut connection让网络学习残差映射而非直接映射，成功训练上百层网络。',
    methodSketch: '1) 设计残差块：F(x) + x；2) 构建18/34/50/101/152层网络；3) 在ImageNet上验证；4) 推广到检测、分割等任务。',
    evidence: {
      tasks: ['ImageNet分类', 'COCO检测', 'COCO分割'],
      baselines: ['VGG', 'GoogLeNet', 'plain network'],
      metrics: ['Top-1/Top-5 error', 'mAP', '训练效率'],
      keyResults: ['ImageNet top-5错误率3.57%', 'COCO检测mAP提升28%', '152层网络成功训练'],
    },
    assumptions: ['残差连接可以有效缓解梯度消失', '深层网络的表达能力确实更强'],
    limitations: ['参数量大，推理速度受限', '残差连接的设计空间还很大', '对小样本学习效果有限'],
    relevanceToMyResearch: '机器人感知的基础骨干网络，几乎所有视觉感知任务都基于ResNet及其变体。',
    questionsToVerify: ['残差连接为什么有效？', '有没有更优的连接方式？', '轻量化版本的性能损失？'],
    limitationsOrQuestions: '参数量大，推理速度受限；残差连接的设计空间还很大。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: [],
    createdAt: '2026-03-15T08:00:00Z',
    updatedAt: '2026-05-20T12:00:00Z',
  },
  {
    id: 'paper-3d-001',
    title: 'PointNet: Deep Learning on Point Sets for 3D Classification and Segmentation',
    authors: 'Charles R. Qi, Hao Su, Kaichun Mo, Leonidas J. Guibas',
    year: 2017,
    venue: 'CVPR',
    arxivUrl: 'https://arxiv.org/abs/1612.00593',
    pdfUrl: 'https://arxiv.org/pdf/1612.00593',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: 'https://github.com/charlesq34/pointnet',
    areaIds: ['area-3d-perception', 'area-perception'],
    readingStatus: 'reviewed',
    methodKeywords: ['PointNet', 'point cloud', '3D deep learning', 'classification', 'segmentation'],
    oneSentenceSummary: '直接处理点云的深度学习网络，是3D点云理解的开创性工作，为机器人3D感知奠定基础。',
    problem: '3D点云数据无序且不规则，传统CNN无法直接处理，需要找到对点云置换不变的网络架构。',
    coreContribution: '提出PointNet，使用最大池化实现置换不变性，直接处理原始点云，支持分类、分割等任务。',
    methodSketch: '1) 逐点MLP提取点特征；2) 最大池化聚合全局特征（置换不变）；3) 拼接局部与全局特征；4) 输出分类/分割结果。',
    evidence: {
      tasks: ['ModelNet40分类', 'ShapeNet部件分割', '场景语义分割'],
      baselines: ['基于多视图的方法', '基于体素的方法'],
      metrics: ['Overall Accuracy', 'mIoU', '推理速度'],
      keyResults: ['ModelNet40精度89.2%', '推理速度快（可实时）', '直接处理原始点云'],
    },
    assumptions: ['最大池化可以有效捕获全局信息', '点云的局部结构可以通过逐点特征隐式表达'],
    limitations: ['缺乏显式的局部特征提取', '对小目标和细节捕捉能力有限', '大规模点云效率问题'],
    relevanceToMyResearch: '3D点云理解的奠基性工作，是机器人3D感知和场景理解的基础。',
    questionsToVerify: ['如何更好地提取局部特征？', '大规模点云如何高效处理？', '与2D特征如何融合？'],
    limitationsOrQuestions: '缺乏显式的局部特征提取；大规模点云效率问题。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: [],
    createdAt: '2026-03-20T09:00:00Z',
    updatedAt: '2026-05-25T14:00:00Z',
  },
  {
    id: 'paper-dynamic-001',
    title: 'MaskFusion: Real-Time Recognition, Tracking and Reconstruction of Multiple Moving Objects',
    authors: 'Martin Runz, Maud Buffier, Lourdes Agapito',
    year: 2018,
    venue: 'ISMAR',
    arxivUrl: 'https://arxiv.org/abs/1804.09194',
    pdfUrl: 'https://arxiv.org/pdf/1804.09194',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: 'https://github.com/martinrunz/MaskFusion',
    areaIds: ['area-dynamic-scene', 'area-semantic-mapping', 'area-3d-perception'],
    readingStatus: 'skimmed',
    methodKeywords: ['MaskFusion', 'dynamic SLAM', 'semantic SLAM', 'object tracking', 'reconstruction'],
    oneSentenceSummary: '实时动态场景SLAM系统，结合语义分割和物体级跟踪重建，处理动态环境中的SLAM问题。',
    problem: '传统SLAM假设场景静态，动态物体会导致严重的定位漂移和重建错误，需要处理动态场景的能力。',
    coreContribution: '提出MaskFusion，结合实例分割与物体级跟踪重建，在动态场景中同时实现静态建图和动态物体跟踪。',
    methodSketch: '1) Mask R-CNN提取物体实例分割；2) 每个物体独立跟踪和重建；3) 静态背景与动态物体分离；4) 实时运行。',
    evidence: {
      tasks: ['动态场景重建', '物体跟踪', '静态建图'],
      baselines: ['KinectFusion', 'DynamicFusion'],
      metrics: ['重建精度', '跟踪成功率', '运行帧率'],
      keyResults: ['实时处理动态场景', '物体级语义重建', '动态物体不影响静态建图'],
    },
    assumptions: ['实例分割可以检测到所有动态物体', '物体运动是刚体运动'],
    limitations: ['依赖实例分割的准确性', '非刚体运动处理困难', '计算量较大'],
    relevanceToMyResearch: '动态场景SLAM的经典工作，对理解动态环境中的定位和建图很有启发。',
    questionsToVerify: ['实例分割失败时如何处理？', '非刚体运动如何建模？', '能否与VIO结合？'],
    limitationsOrQuestions: '依赖实例分割的准确性；非刚体运动处理困难。',
    judgementLevel: 'useful',
    inspiredIdeaIds: [],
    createdAt: '2026-05-05T10:00:00Z',
    updatedAt: '2026-06-20T11:00:00Z',
  },
  {
    id: 'paper-semantic-001',
    title: 'SemanticFusion: Dense 3D Semantic Mapping with Convolutional Neural Networks',
    authors: 'John McCormac, Ankur Handa, Andrew Davison, Stefan Leutenegger',
    year: 2017,
    venue: 'ICRA',
    arxivUrl: 'https://arxiv.org/abs/1609.05130',
    pdfUrl: 'https://arxiv.org/pdf/1609.05130',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: 'https://github.com/seaun163/semanticfusion',
    areaIds: ['area-semantic-mapping', 'area-3d-perception', 'area-slam'],
    readingStatus: 'skimmed',
    methodKeywords: ['SemanticFusion', 'semantic mapping', 'dense reconstruction', 'CNN', 'CRF'],
    oneSentenceSummary: '将CNN语义分割与稠密SLAM结合，实现实时3D语义地图构建，是语义SLAM的代表性工作。',
    problem: '传统SLAM只构建几何地图，缺乏语义信息，限制了机器人在真实场景中的理解和交互能力。',
    coreContribution: '提出SemanticFusion，将2D CNN语义预测与ElasticFusion稠密建图结合，通过多帧融合和CRF优化构建3D语义地图。',
    methodSketch: '1) ElasticFusion实时稠密重建；2) 每帧用CNN预测2D语义；3) 反投影到3D并融合多帧预测；4) CRF优化3D语义标签。',
    evidence: {
      tasks: ['3D语义地图构建', '场景理解', '室内重建'],
      baselines: ['单帧2D语义', '基于体素的方法'],
      metrics: ['3D mIoU', '重建精度', '运行效率'],
      keyResults: ['3D语义精度显著优于单帧', '实时运行（~10fps）', '稠密语义地图'],
    },
    assumptions: ['2D语义分割可以有效反投影到3D', '多帧融合可以提升语义精度'],
    limitations: ['依赖2D语义分割的质量', '室内场景为主', '计算量较大'],
    relevanceToMyResearch: '语义SLAM的经典工作，是机器人环境理解从几何到语义的重要一步。',
    questionsToVerify: ['室外场景效果如何？', '如何处理动态物体？', '语义信息能否反哺定位？'],
    limitationsOrQuestions: '依赖2D语义分割的质量；室内场景为主。',
    judgementLevel: 'useful',
    inspiredIdeaIds: [],
    createdAt: '2026-05-10T09:00:00Z',
    updatedAt: '2026-06-25T13:00:00Z',
  },
  {
    id: 'paper-imitation-001',
    title: 'Generative Adversarial Imitation Learning',
    authors: 'Jonathan Ho, Stefano Ermon',
    year: 2016,
    venue: 'NeurIPS',
    arxivUrl: 'https://arxiv.org/abs/1606.03476',
    pdfUrl: 'https://arxiv.org/pdf/1606.03476',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: '',
    areaIds: ['area-imitation', 'area-robot-learning'],
    readingStatus: 'reviewed',
    methodKeywords: ['GAIL', 'imitation learning', 'GAN', 'inverse reinforcement learning'],
    oneSentenceSummary: '将GAN思想引入模仿学习，直接从专家演示中学习策略，避免显式奖励函数设计，是模仿学习的里程碑工作。',
    problem: '传统模仿学习需要显式设计奖励函数（逆强化学习），计算复杂且难以扩展到高维任务。',
    coreContribution: '提出GAIL，通过生成对抗框架直接学习策略，将模仿学习转化为判别器-生成器博弈，避免了中间的奖励函数步骤。',
    methodSketch: '1) 判别器区分专家轨迹和生成轨迹；2) 生成器（策略）试图欺骗判别器；3) 类似GAN的交替训练；4) 加入熵正则化稳定训练。',
    evidence: {
      tasks: ['MuJoCo控制', 'Atari游戏'],
      baselines: ['行为克隆BC', '逆强化学习IRL', 'Guided Cost Learning'],
      metrics: ['任务成功率', '与专家策略的相似度', '样本效率'],
      keyResults: ['性能超过行为克隆', '无需显式奖励函数', '适应多种控制任务'],
    },
    assumptions: ['专家演示是最优或近似最优的', '环境是马尔可夫决策过程', 'GAN训练可以稳定收敛'],
    limitations: ['训练不稳定（GAN通病）', '需要大量专家演示', '环境假设可能不成立'],
    relevanceToMyResearch: '模仿学习的基础工作，对理解机器人技能学习和策略迁移很重要。',
    questionsToVerify: ['如何提升训练稳定性？', '少量专家数据下如何学习？', '能否与VLA结合？'],
    limitationsOrQuestions: '训练不稳定（GAN通病）；需要大量专家演示。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: [],
    createdAt: '2026-04-10T08:00:00Z',
    updatedAt: '2026-06-15T10:00:00Z',
  },
  {
    id: 'paper-embodied-001',
    title: 'Embodied Question Answering',
    authors: 'Abhishek Das, Samyak Datta, Georgia Gkioxari, Stefan Lee, Devi Parikh, Dhruv Batra',
    year: 2018,
    venue: 'CVPR',
    arxivUrl: 'https://arxiv.org/abs/1711.11543',
    pdfUrl: 'https://arxiv.org/pdf/1711.11543',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: 'https://github.com/facebookresearch/EmbodiedQA',
    areaIds: ['area-embodied-ai', 'area-vla'],
    readingStatus: 'skimmed',
    methodKeywords: ['Embodied AI', 'VQA', 'navigation', 'question answering', 'House3D'],
    oneSentenceSummary: '提出具身问答任务，智能体需要在3D环境中主动探索并回答问题，是具身AI的代表性工作。',
    problem: '传统VQA只看单张图片，缺乏主动感知和空间理解能力，与真实机器人场景差距大。',
    coreContribution: '提出Embodied QA任务设置和评估框架，智能体需要在3D环境中导航探索、收集信息并回答问题。',
    methodSketch: '1) House3D环境（真实室内场景3D重建）；2) 智能体接收第一视角图像和问题；3) 学习导航策略收集信息；4) 基于探索到的信息回答问题。',
    evidence: {
      tasks: ['室内导航+问答', '物体寻找', '空间推理'],
      baselines: ['单图VQA', '随机探索', '分层策略'],
      metrics: ['问答准确率', '导航效率', '探索覆盖率'],
      keyResults: ['主动探索优于单图VQA', '需要空间推理能力', '任务难度合理'],
    },
    assumptions: ['3D仿真环境可以代表真实场景', '智能体可以通过探索获取足够信息'],
    limitations: ['仿真与真实的差距', '问题类型有限', '视觉理解能力是瓶颈'],
    relevanceToMyResearch: '具身AI的经典任务设置，对理解机器人智能体的感知-决策闭环很有启发。',
    questionsToVerify: ['如何迁移到真实机器人？', '多轮对话场景如何处理？', '与VLA的结合点在哪里？'],
    limitationsOrQuestions: '仿真与真实的差距；问题类型有限。',
    judgementLevel: 'useful',
    inspiredIdeaIds: [],
    createdAt: '2026-05-20T10:00:00Z',
    updatedAt: '2026-06-28T16:00:00Z',
  },
  {
    id: 'paper-foundation-001',
    title: 'RT-1: Robotics Transformer for Real-World Control at Scale',
    authors: 'Anthony Brohan, Noah Brown, Justice Carbajal, et al.',
    year: 2022,
    venue: 'RSS',
    arxivUrl: 'https://arxiv.org/abs/2212.06817',
    pdfUrl: 'https://arxiv.org/pdf/2212.06817',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: '',
    areaIds: ['area-foundation', 'area-vla', 'area-robot-learning'],
    readingStatus: 'reviewed',
    methodKeywords: ['RT-1', 'robotics transformer', 'multi-task learning', 'real-world robot'],
    oneSentenceSummary: '大规模机器人操作的Transformer模型，在真实机器人上学习700+任务，是机器人基础模型的先驱工作。',
    problem: '机器人策略通常针对单一任务，数据利用效率低，难以泛化到新任务和新场景。',
    coreContribution: '提出RT-1，在大规模真实机器人数据上训练的Transformer模型，支持700+任务，具备一定零样本泛化能力。',
    methodSketch: '1) 13万条真实机器人演示数据；2) Token化图像和指令；3) Transformer解码动作token；4) 多任务联合训练。',
    evidence: {
      tasks: ['700+机器人操作任务', '零样本新任务泛化', '干扰鲁棒性测试'],
      baselines: ['BC-Z', 'Gato', '单任务策略'],
      metrics: ['任务成功率', '零样本泛化率', '鲁棒性'],
      keyResults: ['700+任务成功率97%', '未见任务零样本泛化', '对干扰有鲁棒性'],
    },
    assumptions: ['大规模真实机器人数据可以覆盖广泛任务', 'Transformer可以学习通用的机器人操作技能'],
    limitations: ['数据采集成本极高', '主要是桌面操作任务', '推理速度慢'],
    relevanceToMyResearch: '机器人基础模型的开创性工作，理解从单任务到多任务到通用机器人的演进路径。',
    questionsToVerify: ['数据效率能否提升？', '能否扩展到更多任务类型？', '与VLA的关系？'],
    limitationsOrQuestions: '数据采集成本极高；主要是桌面操作任务。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: [],
    createdAt: '2026-04-01T08:00:00Z',
    updatedAt: '2026-06-20T15:00:00Z',
  },
  {
    id: 'paper-dexterous-001',
    title: 'Learning Dexterous In-Hand Manipulation',
    authors: 'OpenAI: Marcin Andrychowicz, Bowen Baker, Maciek Chociej, et al.',
    year: 2020,
    venue: 'IJRR',
    arxivUrl: 'https://arxiv.org/abs/1912.04344',
    pdfUrl: 'https://arxiv.org/pdf/1912.04344',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: '',
    areaIds: ['area-dexterous', 'area-robot-learning', 'area-sim2real'],
    readingStatus: 'skimmed',
    methodKeywords: ['dexterous manipulation', 'in-hand manipulation', 'reinforcement learning', 'sim-to-real', 'Shadow Hand'],
    oneSentenceSummary: '用强化学习在仿真中训练灵巧手操作，通过sim-to-real迁移到真实Shadow Hand，是灵巧操作的里程碑工作。',
    problem: '灵巧手操作维度高、动力学复杂，传统方法难以实现复杂的手上操作。',
    coreContribution: '使用RL在仿真中训练灵巧手操作物体，结合域随机化实现sim-to-real迁移，在真实Shadow Hand上成功完成复杂操作。',
    methodSketch: '1) 仿真环境中训练RL策略；2) 大量域随机化（物理参数、视觉等）；3) 目标姿态随机化提升泛化；4) 迁移到真实机器人。',
    evidence: {
      tasks: ['物体旋转', '物体重定向', '多物体操作'],
      baselines: ['传统控制方法', '无域随机化的RL'],
      metrics: ['操作成功率', 'sim-to-real迁移率', '鲁棒性'],
      keyResults: ['真实灵巧手成功操作物体', '零样本sim-to-real', '对未知物体有泛化性'],
    },
    assumptions: ['域随机化可以覆盖真实环境分布', '仿真环境足够准确', 'RL策略可以收敛到有效策略'],
    limitations: ['训练成本极高', '仿真训练时间长', '操作速度慢'],
    relevanceToMyResearch: '灵巧操作和sim-to-real的经典工作，对理解高自由度机器人技能学习很重要。',
    questionsToVerify: ['能否提升样本效率？', '更复杂的操作能否学习？', '与视觉反馈结合的效果？'],
    limitationsOrQuestions: '训练成本极高；操作速度慢。',
    judgementLevel: 'useful',
    inspiredIdeaIds: [],
    createdAt: '2026-05-15T09:00:00Z',
    updatedAt: '2026-06-30T10:00:00Z',
  },
  {
    id: 'paper-sim2real-001',
    title: 'Domain Randomization for Transferring Deep Neural Networks from Simulation to the Real World',
    authors: 'Josh Tobin, Rachel Fong, Alex Ray, Jonas Schneider, Wojciech Zaremba, Pieter Abbeel',
    year: 2017,
    venue: 'IROS',
    arxivUrl: 'https://arxiv.org/abs/1703.06907',
    pdfUrl: 'https://arxiv.org/pdf/1703.06907',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: '',
    areaIds: ['area-sim2real', 'area-robot-learning', 'area-perception'],
    readingStatus: 'reviewed',
    methodKeywords: ['domain randomization', 'sim-to-real', 'transfer learning', 'object detection'],
    oneSentenceSummary: '提出域随机化方法，通过在仿真中随机化视觉参数训练模型，实现零样本sim-to-real迁移。',
    problem: '仿真与真实环境存在视觉差异（reality gap），在仿真中训练的模型在真实环境中效果差。',
    coreContribution: '提出域随机化（Domain Randomization），在仿真中随机化光照、纹理、物体位置等参数，让模型学习到不变特征，零样本迁移到真实。',
    methodSketch: '1) 构建仿真环境；2) 随机化光照、纹理、相机角度等视觉参数；3) 生成大量随机化数据训练模型；4) 直接在真实环境中测试。',
    evidence: {
      tasks: ['物体检测', '物体定位', '机器人抓取'],
      baselines: ['真实数据训练', '无随机化的仿真数据'],
      metrics: ['检测精度mAP', '定位误差', '抓取成功率'],
      keyResults: ['零样本迁移到真实环境', '性能接近真实数据训练', '无需真实标注数据'],
    },
    assumptions: ['随机化范围可以覆盖真实环境分布', '模型可以从随机化数据中学到不变特征'],
    limitations: ['随机化参数设计需要经验', '计算量大', '部分维度难以随机化'],
    relevanceToMyResearch: 'sim-to-real的基础性工作，域随机化是机器人视觉和控制中最常用的sim-to-real技术之一。',
    questionsToVerify: ['如何自动选择随机化参数？', '域随机化与域适应的结合？', '物理参数随机化的效果？'],
    limitationsOrQuestions: '随机化参数设计需要经验；计算量大。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: [],
    createdAt: '2026-04-05T08:00:00Z',
    updatedAt: '2026-06-10T12:00:00Z',
  },
  {
    id: 'paper-perception-002',
    title: 'You Only Look Once: Unified, Real-Time Object Detection',
    authors: 'Joseph Redmon, Santosh Divvala, Ross Girshick, Ali Farhadi',
    year: 2016,
    venue: 'CVPR',
    arxivUrl: 'https://arxiv.org/abs/1506.02640',
    pdfUrl: 'https://arxiv.org/pdf/1506.02640',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: '',
    areaIds: ['area-perception', 'area-3d-perception'],
    readingStatus: 'reviewed',
    methodKeywords: ['YOLO', 'object detection', 'real-time', 'single-stage detector'],
    oneSentenceSummary: '单阶段实时目标检测算法，将检测统一为回归问题，速度远超传统两阶段方法，是机器人实时感知的基础。',
    problem: '传统目标检测（R-CNN系列）是两阶段的，速度慢，难以满足机器人实时感知需求。',
    coreContribution: '提出YOLO，将目标检测转化为单个回归问题，从图像像素直接预测边界框和类别概率，实现实时检测。',
    methodSketch: '1) 将图像划分为S×S网格；2) 每个网格预测B个边界框和置信度；3) 单CNN端到端训练；4) 非极大值抑制后处理。',
    evidence: {
      tasks: ['PASCAL VOC', 'COCO目标检测'],
      baselines: ['Faster R-CNN', 'SSD', 'DPM'],
      metrics: ['mAP', 'FPS', '推理速度'],
      keyResults: ['VOC上45帧每秒', '速度是Faster R-CNN的10x', '检测精度有竞争力'],
    },
    assumptions: ['目标检测可以作为回归问题处理', '网格划分可以覆盖所有目标'],
    limitations: ['小目标检测效果差', '边界框定位精度不如两阶段', '密集场景效果不好'],
    relevanceToMyResearch: '实时目标检测的奠基性工作，是机器人感知系统中目标检测的标准选择。',
    questionsToVerify: ['小目标检测如何改进？', '与3D检测的结合？', '最新版本（YOLOv8等）的改进点？'],
    limitationsOrQuestions: '小目标检测效果差；边界框定位精度不如两阶段。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: [],
    createdAt: '2026-03-25T09:00:00Z',
    updatedAt: '2026-06-05T14:00:00Z',
  },
  {
    id: 'paper-3d-002',
    title: 'VoxelNet: End-to-End Learning for Point Cloud Based 3D Object Detection',
    authors: 'Yin Zhou, Oncel Tuzel',
    year: 2018,
    venue: 'CVPR',
    arxivUrl: 'https://arxiv.org/abs/1711.06396',
    pdfUrl: 'https://arxiv.org/pdf/1711.06396',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: '',
    areaIds: ['area-3d-perception', 'area-perception'],
    readingStatus: 'skimmed',
    methodKeywords: ['VoxelNet', '3D object detection', 'point cloud', 'LiDAR', 'voxel feature encoding'],
    oneSentenceSummary: '基于体素的3D目标检测网络，端到端学习点云特征，是激光雷达3D检测的开创性工作。',
    problem: '3D点云目标检测依赖手工特征（如BEV投影），难以充分利用3D空间信息。',
    coreContribution: '提出VoxelNet，将点云划分为体素，用VFE层学习体素特征，再用3D CNN检测，实现端到端3D目标检测。',
    methodSketch: '1) 点云体素化；2) Voxel Feature Encoding（VFE）学习体素内点特征；3) 3D卷积中间层；4) RPN输出检测结果。',
    evidence: {
      tasks: ['KITTI 3D目标检测', '鸟瞰图检测'],
      baselines: ['MV3D', 'AVOD', '基于手工特征的方法'],
      metrics: ['3D mAP', 'BEV mAP', '推理速度'],
      keyResults: ['KITTI 3D检测SOTA', '端到端学习无需手工特征', 'BEV检测精度高'],
    },
    assumptions: ['体素化可以有效表示3D空间', 'VFE可以提取体素内的有效特征'],
    limitations: ['体素化导致信息损失', '计算量大（3D卷积）', '对稀疏点云效果差'],
    relevanceToMyResearch: '3D点云目标检测的经典工作，是自动驾驶和机器人3D感知的重要基础。',
    questionsToVerify: ['如何提升稀疏点云下的检测效果？', '与图像融合的效果？', '实时性如何提升？'],
    limitationsOrQuestions: '体素化导致信息损失；计算量大（3D卷积）。',
    judgementLevel: 'useful',
    inspiredIdeaIds: [],
    createdAt: '2026-05-25T10:00:00Z',
    updatedAt: '2026-06-28T11:00:00Z',
  },
  {
    id: 'paper-vla-003',
    title: 'RT-X: Robotics Transformer for Real-World Control at Scale',
    authors: 'Anthony Brohan, Noah Brown, Justice Carbajal, et al.',
    year: 2023,
    venue: 'arXiv',
    arxivUrl: 'https://arxiv.org/abs/2306.05803',
    pdfUrl: 'https://arxiv.org/pdf/2306.05803',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: '',
    areaIds: ['area-vla', 'area-foundation'],
    readingStatus: 'deep_reading',
    methodKeywords: ['RT-X', 'robotics transformer', 'multi-task', 'real-world'],
    oneSentenceSummary: 'RT-1的扩展版本，在更大规模数据上训练，支持更多任务类型，是VLA发展的重要里程碑。',
    problem: 'RT-1只在单一机器人平台上训练，泛化能力有限，难以扩展到更多任务和平台。',
    coreContribution: '提出RT-X，在100+机器人平台的大规模数据上训练Transformer模型，实现跨平台、跨任务的通用机器人控制。',
    methodSketch: '1) 收集100+机器人平台的大规模演示数据；2) 统一动作表示和视觉输入；3) Transformer架构学习通用技能；4) 零样本迁移到新平台和新任务。',
    evidence: {
      tasks: ['多平台操作任务', '零样本新任务', '跨平台迁移'],
      baselines: ['RT-1', 'BC', 'Gato'],
      metrics: ['跨平台成功率', '零样本泛化率', '数据效率'],
      keyResults: ['跨100+平台零样本迁移', '未见任务成功率提升', '数据效率显著提升'],
    },
    assumptions: ['大规模多平台数据可以学习通用技能', '统一动作表示可以跨平台工作'],
    limitations: ['数据采集成本极高', '部分平台数据质量参差不齐', '复杂任务泛化能力有限'],
    relevanceToMyResearch: 'RT-X是VLA从单平台到多平台的关键一步，理解其训练策略对设计通用机器人模型很重要。',
    questionsToVerify: ['数据质量对模型性能的影响？', '能否进一步扩展到更多平台？', '与OpenVLA的对比？'],
    limitationsOrQuestions: '数据采集成本极高；部分平台数据质量参差不齐。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: [],
    createdAt: '2026-07-05T10:00:00Z',
    updatedAt: '2026-07-06T14:00:00Z',
  },
  {
    id: 'paper-vla-004',
    title: 'Gemini for Robotics: Multimodal Reasoning for Robot Control',
    authors: 'Google DeepMind',
    year: 2024,
    venue: 'arXiv',
    arxivUrl: 'https://arxiv.org/abs/2403.05536',
    pdfUrl: 'https://arxiv.org/pdf/2403.05536',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: '',
    areaIds: ['area-vla', 'area-foundation'],
    readingStatus: 'skimmed',
    methodKeywords: ['Gemini', 'multimodal', 'robot control', 'reasoning'],
    oneSentenceSummary: 'Google Gemini模型在机器人控制中的应用，展示了大模型推理能力向机器人操作的迁移。',
    problem: '现有VLA模型在复杂任务规划和长程推理方面能力有限，难以处理需要多步推理的机器人任务。',
    coreContribution: '将Gemini大模型用于机器人控制，利用其强大的推理能力实现复杂任务规划和多模态理解。',
    methodSketch: '1) 使用Gemini处理多模态输入（图像、语言、传感器）；2) 利用推理能力进行任务规划；3) 输出高级指令给底层控制器；4) 实现端到端机器人控制。',
    evidence: {
      tasks: ['复杂操作任务', '多步推理任务', '多模态理解'],
      baselines: ['RT-2', 'RT-X'],
      metrics: ['复杂任务成功率', '推理步数', '泛化能力'],
      keyResults: ['复杂任务成功率显著提升', '多步推理能力强', '多模态理解能力好'],
    },
    assumptions: ['大模型推理能力可以迁移到机器人控制', '高级指令可以准确控制底层执行器'],
    limitations: ['推理速度较慢', '需要大量计算资源', '部分任务需要微调'],
    relevanceToMyResearch: 'Gemini代表了大模型在机器人领域的最新应用，是VLA方向的重要参考。',
    questionsToVerify: ['与RT系列的性能对比？', '推理速度能否优化？', '小模型能否达到类似效果？'],
    limitationsOrQuestions: '推理速度较慢；需要大量计算资源。',
    judgementLevel: 'useful',
    inspiredIdeaIds: [],
    createdAt: '2026-07-06T09:00:00Z',
    updatedAt: '2026-07-06T09:00:00Z',
  },
  {
    id: 'paper-diffusion-002',
    title: 'Diffusion Policy: Visuomotor Policy Learning via Action Diffusion',
    authors: 'Cheng Chi, Siyuan Feng, Yilun Du, et al.',
    year: 2023,
    venue: 'RSS',
    arxivUrl: 'https://arxiv.org/abs/2303.04137',
    pdfUrl: 'https://arxiv.org/pdf/2303.04137',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: 'https://github.com/columbia-ai-robotics/diffusion_policy',
    areaIds: ['area-diffusion-policy', 'area-robot-learning'],
    readingStatus: 'reviewed',
    methodKeywords: ['diffusion policy', 'action diffusion', 'visuomotor', 'robotic manipulation'],
    oneSentenceSummary: '扩散策略的后续工作，进一步验证了扩散模型在多模态动作建模上的优势，是扩散策略的经典参考。',
    problem: '传统策略学习方法难以建模多模态动作分布，在需要多种解决方案的任务中表现受限。',
    coreContribution: '系统验证了扩散策略在多种机器人操作任务上的优势，对比了不同扩散架构的效果。',
    methodSketch: '1) 构建动作扩散模型；2) 在多种机器人任务上训练；3) 对比BC、GMM等方法；4) 分析扩散步数与性能的权衡。',
    evidence: {
      tasks: ['PushT', 'Kitchen', 'Robotics manipulation', 'Multi-modal tasks'],
      baselines: ['BC', 'GMM', 'IL', 'RL'],
      metrics: ['Task success rate', 'Action diversity', 'Sample efficiency'],
      keyResults: ['多模态任务成功率提升30%+', '动作分布更多样', '样本效率优于RL'],
    },
    assumptions: ['扩散模型可以准确建模动作分布', '足够的训练数据', '动作空间适合扩散建模'],
    limitations: ['推理速度慢（50步扩散）', '训练不稳定', '动作空间维度高时效果下降'],
    relevanceToMyResearch: '扩散策略是机器人学习的新兴方向，值得深入研究其加速方法。',
    questionsToVerify: ['少步扩散能否保持性能？', '训练稳定性如何改进？', '与VLA的结合？'],
    limitationsOrQuestions: '推理速度慢（50步扩散）；训练不稳定。',
    judgementLevel: 'idea_source',
    inspiredIdeaIds: ['idea-diffusion-fast'],
    createdAt: '2026-07-04T10:00:00Z',
    updatedAt: '2026-07-05T16:00:00Z',
  },
  {
    id: 'paper-embodied-002',
    title: 'EmbodiedGPT: Vision-Language Pre-training via Embodied Chain-of-Thought',
    authors: 'Yongqiang Tang, et al.',
    year: 2023,
    venue: 'arXiv',
    arxivUrl: 'https://arxiv.org/abs/2308.05656',
    pdfUrl: 'https://arxiv.org/pdf/2308.05656',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: '',
    areaIds: ['area-embodied-ai', 'area-vla'],
    readingStatus: 'skimmed',
    methodKeywords: ['EmbodiedGPT', 'vision-language', 'embodied AI', 'chain-of-thought'],
    oneSentenceSummary: '通过具身思维链进行视觉语言预训练，提升模型在具身任务上的推理和规划能力。',
    problem: '现有视觉语言模型缺乏具身交互经验，在需要物理世界交互的任务中表现不佳。',
    coreContribution: '提出EmbodiedGPT，通过在虚拟环境中执行具身思维链来预训练视觉语言模型，提升具身任务能力。',
    methodSketch: '1) 在虚拟环境中生成具身思维链数据；2) 用这些数据预训练视觉语言模型；3) 在真实具身任务上验证；4) 分析思维链的作用。',
    evidence: {
      tasks: ['具身问答', '导航', '操作', '规划'],
      baselines: ['GPT-4V', 'CLIP', '传统VLA'],
      metrics: ['任务成功率', '推理步数', '规划质量'],
      keyResults: ['具身任务成功率大幅提升', '推理能力增强', '零样本泛化能力好'],
    },
    assumptions: ['具身思维链可以提升模型的物理理解', '虚拟环境预训练可以迁移到真实场景'],
    limitations: ['虚拟与真实的差距', '计算成本高', '需要大量交互数据'],
    relevanceToMyResearch: '具身思维链是提升VLA推理能力的重要方向，值得关注。',
    questionsToVerify: ['与真实机器人数据的对比？', '能否扩展到更多任务？', '计算效率如何？'],
    limitationsOrQuestions: '虚拟与真实的差距；计算成本高。',
    judgementLevel: 'useful',
    inspiredIdeaIds: [],
    createdAt: '2026-07-05T08:00:00Z',
    updatedAt: '2026-07-05T08:00:00Z',
  },
  {
    id: 'paper-foundation-002',
    title: 'PaLM-E: An Embodied Multimodal Language Model',
    authors: 'Danny Driess, Fei Xia, Mehdi S. M. Sajjadi, et al.',
    year: 2023,
    venue: 'ICLR',
    arxivUrl: 'https://arxiv.org/abs/2303.03378',
    pdfUrl: 'https://arxiv.org/pdf/2303.03378',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: '',
    areaIds: ['area-foundation', 'area-embodied-ai'],
    readingStatus: 'reviewed',
    methodKeywords: ['PaLM-E', 'embodied AI', 'multimodal language model', 'robotics'],
    oneSentenceSummary: '将语言模型与机器人感知结合，实现端到端的具身智能，是机器人基础模型的重要工作。',
    problem: '语言模型和机器人感知模型通常是分开训练的，难以实现端到端的具身智能。',
    coreContribution: '提出PaLM-E，一种具身多模态语言模型，将语言模型扩展到机器人感知输入，实现端到端的机器人控制和推理。',
    methodSketch: '1) 将PaLM语言模型扩展为多模态输入；2) 融合图像、深度、机器人状态等感知信息；3) 输出自然语言指令或动作；4) 在多种具身任务上验证。',
    evidence: {
      tasks: ['导航', '操作', '问答', '规划'],
      baselines: ['GPT-4', 'CLIP', '传统机器人方法'],
      metrics: ['任务成功率', '推理能力', '泛化能力'],
      keyResults: ['多种具身任务统一处理', '推理能力强', '跨任务泛化'],
    },
    assumptions: ['语言模型可以作为具身智能的核心', '多模态输入可以有效融合'],
    limitations: ['模型参数量大', '推理速度慢', '需要大量具身数据'],
    relevanceToMyResearch: 'PaLM-E是机器人基础模型的代表性工作，理解其架构对设计未来机器人模型很有启发。',
    questionsToVerify: ['与RT系列的对比？', '模型大小与性能的权衡？', '数据效率如何？'],
    limitationsOrQuestions: '模型参数量大；推理速度慢。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: [],
    createdAt: '2026-07-03T10:00:00Z',
    updatedAt: '2026-07-04T14:00:00Z',
  },
  {
    id: 'paper-world-models-002',
    title: 'Generative World Models for Planning',
    authors: 'Danijar Hafner, et al.',
    year: 2024,
    venue: 'arXiv',
    arxivUrl: 'https://arxiv.org/abs/2401.03459',
    pdfUrl: 'https://arxiv.org/pdf/2401.03459',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: '',
    areaIds: ['area-world-models', 'area-robot-learning'],
    readingStatus: 'skimmed',
    methodKeywords: ['generative world model', 'planning', 'model-based RL', 'robotics'],
    oneSentenceSummary: '生成式世界模型在机器人规划中的最新进展，展示了世界模型在长程规划中的潜力。',
    problem: '传统世界模型在长程规划和复杂环境建模方面能力有限，难以应对真实机器人场景。',
    coreContribution: '提出改进的生成式世界模型，在长程规划任务上取得显著提升，验证了世界模型在机器人规划中的价值。',
    methodSketch: '1) 改进生成式模型架构；2) 优化规划算法；3) 在复杂机器人任务上验证；4) 分析规划长度与性能的关系。',
    evidence: {
      tasks: ['长程规划', '复杂操作', '动态环境'],
      baselines: ['DreamerV3', '传统规划方法'],
      metrics: ['规划长度', '任务成功率', '计算效率'],
      keyResults: ['长程规划能力提升', '复杂任务成功率高', '计算效率优化'],
    },
    assumptions: ['生成式模型可以准确建模环境动态', '规划在模型中有效'],
    limitations: ['长时间预测准确性下降', '计算成本高', '对训练数据要求高'],
    relevanceToMyResearch: '世界模型是机器人规划的重要方向，值得关注其最新进展。',
    questionsToVerify: ['在真实机器人上的表现？', '与VLA的结合？', '计算效率如何进一步提升？'],
    limitationsOrQuestions: '长时间预测准确性下降；计算成本高。',
    judgementLevel: 'useful',
    inspiredIdeaIds: [],
    createdAt: '2026-07-04T08:00:00Z',
    updatedAt: '2026-07-04T08:00:00Z',
  },
];

export const mockObservations: Observation[] = [
  {
    id: 'obs-001',
    content: '对比学习论文假设类别分布均衡，但在长尾场景下这个假设不成立',
    type: 'paper',
    keywords: ['对比学习', '长尾分布', '分布假设'],
    potentialIssue: '长尾场景下对比学习的有效性',
    researchValue: 'high',
    researchValueReason: '这是一个基础假设的漏洞，如果成立可能影响广泛',
    suggestedAction: '搜索长尾+对比学习的相关工作',
    createdAt: '2026-07-01T10:00:00Z',
    context: '来自论文阅读笔记',
    signals: ['数据异常', '方法局限性'],
  },
  {
    id: 'obs-002',
    content: '复现时发现模型在类别 45 上准确率只有 12%，远低于论文报告的 67%',
    type: 'experiment',
    keywords: ['复现失败', '长尾类别', '性能差异'],
    potentialIssue: '报告指标是否选择性展示',
    researchValue: 'medium',
    researchValueReason: '可能是复现问题也可能是真实问题',
    suggestedAction: '检查代码，如果确认不是 bug 则值得深挖',
    createdAt: '2026-07-01T14:30:00Z',
    context: '来自实验日志',
    signals: ['性能瓶颈', '未解决问题'],
  },
  {
    id: 'obs-003',
    content: '师兄说这个领域大家都在做损失函数改进，数据层面的工作几乎没人做',
    type: 'discussion',
    keywords: ['方法分布', '损失函数', '数据增强'],
    potentialIssue: '为什么数据层面被忽视？是被证明无效还是没人尝试？',
    researchValue: 'high',
    researchValueReason: '如果真没人做，可能是差异化切入点',
    suggestedAction: '搜索数据增强+长尾识别的工作',
    createdAt: '2026-07-02T09:00:00Z',
    context: '来自团队讨论',
    signals: ['潜在改进点', '关键假设'],
  },
];

export const mockIdeaCards: IdeaCard[] = [
  {
    id: 'idea-vla-speedup',
    title: 'VLA推理加速：分层动作解码策略',
    status: 'active',
    researchQuestion: '能否通过分层动作解码，在保持VLA泛化能力的同时大幅提升推理速度？',
    coreHypothesis: '将VLA动作输出分解为"高层语义动作+低层轨迹生成"两层，高层用大模型推理，低层用轻量模型执行，可以在不损失太多泛化性的情况下实现实时控制。',
    hypothesis: '将VLA动作输出分解为"高层语义动作+低层轨迹生成"两层，高层用大模型推理，低层用轻量模型执行，可以在不损失太多泛化性的情况下实现实时控制。',
    whyItMatters: 'VLA是机器人基础模型的核心方向，但当前推理速度（~3s/step）远不能满足实时控制需求（>10Hz），速度瓶颈严重制约了VLA的实际应用。',
    predictions: [],
    failureConditions: [],
    confounders: [],
    evidenceForHypothesis: [
      { id: 'ev-1', content: '分层控制在机器人领域已被广泛验证', source: '文献', isAIGenerated: true },
      { id: 'ev-2', content: 'RT-2显示VLA输出低层动作效率低', source: '论文', isAIGenerated: true },
    ],
    evidenceAgainstHypothesis: [
      { id: 'ev-3', content: '分层可能导致语义与动作的鸿沟', source: 'AI推理', isAIGenerated: true },
      { id: 'ev-4', content: '高层规划的错误会向下传播', source: 'AI推理', isAIGenerated: true },
    ],
    falsificationRisks: [
      { id: 'ev-5', content: '分层架构在未见任务上的泛化性对比', source: '实验验证', isAIGenerated: true },
      { id: 'ev-6', content: '高层语义动作的表示空间设计', source: '研究问题', isAIGenerated: true },
    ],
    biggestRisks: [
      '分层后泛化能力大幅下降，失去VLA的核心优势',
      '高低层接口设计困难，语义鸿沟问题严重',
      '加速效果不明显（<2x），不足以支撑实时应用',
    ],
    survivalScore: 50,
    confidenceScore: 50,
    falsificationStrength: 0,
    sourceObservations: [],
    sourcePaperIds: ['paper-vla-001'],
    areaIds: ['area-vla', 'area-foundation'],
    roboticsTask: '桌面操作（抓取、放置、推动）',
    datasetOrScenario: 'RT-1 / RT-2 数据集 + 自建真实机器人场景',
    baseline: 'RT-2 端到端 VLA',
    evaluationMetric: '任务成功率 + 推理延迟（ms/step）+ 未见任务泛化率',
    nextAction: '在模拟环境中验证分层架构的可行性（预计 1 周）',
    notes: '',
    createdAt: '2026-07-02T14:00:00Z',
    updatedAt: '2026-07-03T09:00:00Z',
  },
  {
    id: 'idea-diffusion-fast',
    title: '快速扩散策略：少步扩散用于实时机器人控制',
    status: 'active',
    researchQuestion: '能否将扩散步数从50步压缩到5步以内，同时保持策略性能，用于实时机器人控制？',
    coreHypothesis: '通过蒸馏或更好的噪声调度，可以用极少的扩散步数（<5步）达到接近全步数的策略性能，从而满足实时控制要求。',
    hypothesis: '通过蒸馏或更好的噪声调度，可以用极少的扩散步数（<5步）达到接近全步数的策略性能，从而满足实时控制要求。',
    whyItMatters: '扩散策略在多模态动作建模上有优势，但推理速度是主要瓶颈。如果能实现少步扩散，将大幅提升扩散策略的实用性。',
    predictions: [],
    failureConditions: [],
    confounders: [],
    evidenceForHypothesis: [
      { id: 'ev-7', content: '图像领域已有少步扩散的成功案例（如LCM）', source: '文献', isAIGenerated: true },
      { id: 'ev-8', content: 'Diffusion Policy展示了扩散在策略学习中的优势', source: '论文', isAIGenerated: true },
    ],
    evidenceAgainstHypothesis: [
      { id: 'ev-9', content: '动作空间维度高，少步扩散可能质量下降严重', source: 'AI推理', isAIGenerated: true },
    ],
    falsificationRisks: [
      { id: 'ev-10', content: '动作空间中少步扩散的性能边界', source: '实验验证', isAIGenerated: true },
    ],
    biggestRisks: [
      '少步扩散后策略性能下降超过10%，得不偿失',
      '蒸馏方法的训练复杂度高，难以复现',
    ],
    survivalScore: 50,
    confidenceScore: 50,
    falsificationStrength: 0,
    sourceObservations: [],
    sourcePaperIds: ['paper-diffusion-001'],
    areaIds: ['area-diffusion-policy', 'area-robot-learning'],
    roboticsTask: '桌面机器人操作任务',
    datasetOrScenario: 'Diffusion Policy 标准测试集（PushT、Kitchen等）',
    baseline: 'Diffusion Policy (50步 DDPM)',
    evaluationMetric: '任务成功率 + 推理时间 + 动作分布多样性',
    nextAction: '在PushT数据集上测试少步扩散的性能变化（预计 3 天）',
    notes: '',
    createdAt: '2026-07-02T16:00:00Z',
    updatedAt: '2026-07-02T16:00:00Z',
  },
  {
    id: 'idea-vio-dynamic',
    title: '动态VIO：动态场景下的鲁棒视觉惯性里程计',
    status: 'active',
    researchQuestion: '如何在高动态场景下保持VIO的定位精度和鲁棒性？',
    coreHypothesis: '通过动态物体检测与特征点分类，将动态物体上的特征点排除或降权，可以显著提升动态场景下VIO的定位精度。',
    hypothesis: '通过动态物体检测与特征点分类，将动态物体上的特征点排除或降权，可以显著提升动态场景下VIO的定位精度。',
    whyItMatters: '真实环境中大量动态物体（人、车）严重影响VIO性能，但现有方法多假设静态环境，动态场景下漂移严重。',
    predictions: [],
    failureConditions: [],
    confounders: [],
    evidenceForHypothesis: [
      { id: 'ev-11', content: '动态物体是VIO主要误差源之一', source: '文献', isAIGenerated: true },
      { id: 'ev-12', content: '语义分割可以有效识别动态物体', source: '事实', isAIGenerated: true },
    ],
    evidenceAgainstHypothesis: [
      { id: 'ev-13', content: '语义分割增加计算量，可能降低实时性', source: 'AI推理', isAIGenerated: true },
      { id: 'ev-14', content: '误检静态物体为动态可能丢失有效特征', source: 'AI推理', isAIGenerated: true },
    ],
    falsificationRisks: [
      { id: 'ev-15', content: '在真实高动态场景下的定量对比实验', source: '实验验证', isAIGenerated: true },
    ],
    biggestRisks: [
      '动态检测的精度不足以支撑VIO改进',
      '计算开销太大，实时性无法保证',
      '提升幅度有限（<10%），不构成独立贡献',
    ],
    survivalScore: 50,
    confidenceScore: 50,
    falsificationStrength: 0,
    sourceObservations: [],
    sourcePaperIds: ['paper-slam-001', 'paper-vio-001'],
    areaIds: ['area-vio', 'area-slam', 'area-dynamic-scene'],
    roboticsTask: '无人机/移动机器人在动态环境中的定位',
    datasetOrScenario: '自采动态场景数据集 + 部分公开数据集（TUM动态序列）',
    baseline: 'VINS-Mono / ORB-SLAM3 标准版本',
    evaluationMetric: 'ATE（绝对轨迹误差）+ 定位失败率 + 处理帧率',
    nextAction: '在TUM动态序列上验证MVE（预计 2 天）',
    notes: '',
    createdAt: '2026-06-25T10:00:00Z',
    updatedAt: '2026-07-01T14:00:00Z',
  },
];

export const mockMVEs: MVE[] = [
  {
    id: 'mve-vio-dynamic-001',
    ideaCardId: 'idea-vio-dynamic',
    mveType: 'sanity_check',
    experimentGoal: '验证动态特征点排除能否在高动态场景下提升VIO定位精度',
    taskDefinition: '移动机器人在动态环境中的定位',
    evaluationProtocol: 'ATE RMSE + 定位失败率 + 处理帧率',
    minimalDesign: '在VINS-Mono基础上加入基于语义分割的动态特征点过滤，在TUM动态序列上对比ATE',
    keyVariables: {
      independent: '动态特征处理方式（无处理 / 直接排除 / 降权）',
      dependent: 'ATE绝对轨迹误差 + 定位失败率',
    },
    controlGroups: [
      'Baseline: VINS-Mono 原版（无动态处理）',
      'Proposed: 语义分割+动态特征排除',
      'Ablation: 动态特征降权（不排除）',
    ],
    baselineReferences: ['VINS-Mono 标准版本'],
    successCriteria: '动态场景下ATE降低30%以上，静态场景下性能不下降',
    failureModes: [],
    failureSignals: [
      'ATE降低幅度<10%',
      '静态场景下ATE反而上升',
      '处理帧率<10Hz，不满足实时要求',
    ],
    minimalEnvOrDataset: 'TUM RGB-D Dataset 动态序列（walking/running）',
    minimalEffort: '基于VINS-Mono修改约200行代码，集成轻量语义分割模型，在TUM数据集测试',
    nextTasks: {
      onPass: '扩展到更多动态场景，设计更精细的动态特征处理策略',
      onFail: '考虑其他动态鲁棒VIO方案（如多几何约束）',
    },
    roboticsTask: '移动机器人在动态环境中的定位',
    datasetOrScenario: 'TUM RGB-D Dataset 动态序列（walking/running）',
    baseline: 'VINS-Mono 标准版本',
    evaluationMetric: 'ATE RMSE + 定位失败率 + 处理帧率',
    minimalComputeNeed: '单台带GPU的工作站，推理~20ms/帧',
    expectedTimeCost: '2-3天（代码修改 + 实验运行）',
    steps: [],
    dataRecords: [],
    resultStatus: 'pending',
    resultNotes: '',
    createdAt: '2026-07-01T14:00:00Z',
  },
];
