import { Observation, IdeaCard, MVE, ResearchArea, Paper, LEGACY_STATUS_MAP } from './types';

export const mockResearchAreas: ResearchArea[] = [
  {
    id: 'area-perception',
    name: 'Robot Perception｜机器人感知',
    description: '机器人感知系统研究，包括视觉、激光、触觉等多模态感知',
    category: '感知',
    keywords: ['robot perception', 'sensing', 'multi-modal'],
    focusQuestions: ['如何提升感知鲁棒性？', '多传感器如何有效融合？'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-02T00:00:00Z',
  },
  {
    id: 'area-state-estimation',
    name: 'State Estimation｜状态估计',
    description: '机器人状态估计理论与方法，包括滤波、优化、传感器融合',
    category: '感知',
    keywords: ['state estimation', 'Kalman filter', 'optimization', 'sensor fusion'],
    focusQuestions: [
      '如何在传感器故障时保持估计稳定性？',
      '多传感器融合的最优架构是什么？',
      '如何处理动态环境下的状态估计？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-02T10:00:00Z',
  },
  {
    id: 'area-slam',
    name: 'SLAM｜同步定位与建图',
    description: '同时定位与地图构建，包括视觉SLAM、激光SLAM、多传感器SLAM',
    category: '感知',
    keywords: ['SLAM', 'localization', 'mapping', 'pose estimation'],
    focusQuestions: [
      '动态环境下SLAM如何保持鲁棒？',
      '如何实现长期自主导航的SLAM？',
      '语义信息如何提升SLAM性能？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-03T00:00:00Z',
  },
  {
    id: 'area-vslam',
    name: 'Visual SLAM｜视觉 SLAM',
    description: '基于视觉的SLAM方法，包括单目、双目、RGBD等',
    category: '感知',
    keywords: ['visual SLAM', 'monocular', 'stereo', 'RGBD', 'ORB'],
    focusQuestions: ['特征点法vs直接法的权衡', '弱纹理环境下的视觉SLAM'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-28T00:00:00Z',
  },
  {
    id: 'area-vio',
    name: 'VIO｜视觉惯性里程计',
    description: '视觉与IMU融合的里程计算法，包括紧耦合、松耦合方案',
    category: '感知',
    keywords: ['VIO', 'visual-inertial', 'IMU', 'odometry', '紧耦合'],
    focusQuestions: [
      'IMU预积分的精度边界在哪里？',
      '如何处理IMU零偏的在线估计？',
      '视觉故障时VIO如何退化？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
  },
  {
    id: 'area-msf',
    name: 'Multi-Sensor Fusion｜多传感器融合',
    description: '多传感器融合理论与方法，包括卡尔曼滤波、因子图、优化方法',
    category: '感知',
    keywords: ['sensor fusion', 'Kalman filter', 'factor graph', 'optimization'],
    focusQuestions: [
      '异构传感器的时间同步如何处理？',
      '传感器故障检测与隔离策略？',
      '融合架构的最优设计原则？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-30T00:00:00Z',
  },
  {
    id: 'area-3d-perception',
    name: '3D Perception｜三维感知',
    description: '三维环境感知，包括3D检测、3D分割、点云处理',
    category: '感知',
    keywords: ['3D detection', 'point cloud', 'LiDAR', '3D segmentation'],
    focusQuestions: ['点云与图像的融合策略', '小目标3D检测的挑战'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-25T00:00:00Z',
  },
  {
    id: 'area-dynamic-scene',
    name: 'Dynamic Scene Understanding｜动态场景理解',
    description: '动态场景的感知与理解，包括运动目标检测、跟踪、预测',
    category: '感知',
    keywords: ['dynamic scene', 'motion detection', 'tracking', 'prediction'],
    focusQuestions: ['动态目标如何影响SLAM？', '运动预测的不确定性建模'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-20T00:00:00Z',
  },
  {
    id: 'area-semantic-mapping',
    name: 'Semantic Mapping｜语义建图',
    description: '语义信息与地图构建的结合，包括语义SLAM、动态语义地图',
    category: '感知',
    keywords: ['semantic mapping', 'semantic SLAM', 'dynamic map'],
    focusQuestions: ['语义信息如何提升导航？', '动态语义地图的更新策略'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-18T00:00:00Z',
  },
  {
    id: 'area-robot-learning',
    name: 'Robot Learning｜机器人学习',
    description: '机器学习在机器人中的应用，包括强化学习、模仿学习等',
    category: '学习',
    keywords: ['robot learning', 'RL', 'imitation learning'],
    focusQuestions: ['Sim-to-Real如何跨越？', '样本效率如何提升？'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-22T00:00:00Z',
  },
  {
    id: 'area-imitation',
    name: 'Imitation Learning｜模仿学习',
    description: '模仿学习方法，包括行为克隆、逆强化学习等',
    category: '学习',
    keywords: ['imitation learning', 'behavior cloning', 'IRL'],
    focusQuestions: ['分布偏移问题如何解决？', '专家数据质量的影响'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-23T00:00:00Z',
  },
  {
    id: 'area-diffusion-policy',
    name: 'Diffusion Policy｜扩散策略',
    description: '扩散模型在机器人策略学习中的应用',
    category: '学习',
    keywords: ['diffusion model', 'policy learning', 'robot manipulation'],
    focusQuestions: [
      '扩散策略的推理速度能否满足实时控制？',
      '扩散策略相比BC/GMM有何本质优势？',
      '如何用扩散建模多模态动作分布？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-02T15:00:00Z',
  },
  {
    id: 'area-vla',
    name: 'VLA｜Vision-Language-Action Models',
    description: '视觉-语言-动作模型，端到端机器人控制大模型',
    category: '前沿',
    keywords: ['VLA', 'vision-language-action', 'robot foundation model', 'RT-2'],
    focusQuestions: [
      'VLA能否泛化到未见任务？',
      '如何用低成本数据训练VLA？',
      'VLA的实时推理如何加速？',
      'VLA与传统控制的边界在哪里？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-03T09:00:00Z',
  },
  {
    id: 'area-world-models',
    name: 'World Models｜世界模型',
    description: '世界模型与基于模型的强化学习，用于机器人规划与控制',
    category: '前沿',
    keywords: ['world model', 'model-based RL', 'planning', 'latent dynamics'],
    focusQuestions: [
      '世界模型能否支撑长程规划？',
      '如何学习可组合的世界模型？',
      '世界模型的不确定性如何量化？',
    ],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-01T14:00:00Z',
  },
  {
    id: 'area-embodied-ai',
    name: 'Embodied AI｜具身智能',
    description: '具身智能研究，包括导航、操作、交互等',
    category: '前沿',
    keywords: ['embodied AI', 'navigation', 'manipulation', 'interaction'],
    focusQuestions: ['具身智能的评估体系？', '通用具身智能的路径？'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-29T00:00:00Z',
  },
  {
    id: 'area-foundation',
    name: 'Robotics Foundation Models｜机器人基础模型',
    description: '机器人领域的基础模型研究，包括预训练、微调、对齐',
    category: '前沿',
    keywords: ['foundation model', 'pre-training', 'fine-tuning', 'alignment'],
    focusQuestions: ['机器人预训练数据如何获取？', '基础模型如何适配具体任务？'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-27T00:00:00Z',
  },
  {
    id: 'area-dexterous',
    name: 'Dexterous Manipulation｜灵巧操作',
    description: '机器人灵巧操作，包括多指手、抓取、操作规划',
    category: '控制',
    keywords: ['dexterous manipulation', 'grasping', 'multi-finger hand'],
    focusQuestions: ['多指手的接触力控制？', '未知物体的抓取策略？'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-21T00:00:00Z',
  },
  {
    id: 'area-sim2real',
    name: 'Sim-to-Real｜仿真到现实迁移',
    description: '仿真到现实的迁移方法，包括域随机化、域适应等',
    category: '学习',
    keywords: ['sim-to-real', 'domain randomization', 'domain adaptation', 'simulation'],
    focusQuestions: ['仿真器的真实性边界？', 'Sim-to-Real的系统性方法论？'],
    isHidden: false,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-24T00:00:00Z',
  },
];

export const mockPapers: Paper[] = [
  {
    id: 'paper-vla-001',
    title: 'RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control',
    authors: 'Anthony Brohan, Noah Brown, Justice Carbajal, et al.',
    year: 2023,
    venue: 'CoRL',
    arxivUrl: 'https://arxiv.org/abs/2307.15818',
    pdfUrl: 'https://arxiv.org/pdf/2307.15818',
    htmlUrl: '',
    feishuNoteUrl: 'https://feishu.cn/docx/xxx-rt2-notes',
    codeUrl: '',
    areaIds: ['area-vla', 'area-foundation'],
    readingStatus: 'deep_reading',
    methodKeywords: ['VLA', 'vision-language', 'robot control', 'RT-2'],
    oneSentenceSummary: '将视觉-语言模型直接输出动作，实现端到端机器人控制，展示了web知识向机器人操作的迁移潜力。',
    relevanceToMyResearch: '核心关注方向，VLA是机器人基础模型的重要路径，需要持续跟踪。',
    limitationsOrQuestions: '推理速度太慢（~3s/step），无法实时控制；未见任务泛化能力有限；需要大量机器人数据。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: ['idea-vla-speedup'],
    createdAt: '2026-06-15T10:00:00Z',
    updatedAt: '2026-07-02T14:00:00Z',
  },
  {
    id: 'paper-vla-002',
    title: 'OpenVLA: An Open-Source Vision-Language-Action Model',
    authors: 'Deepak Pathak, et al.',
    year: 2024,
    venue: 'arXiv',
    arxivUrl: 'https://arxiv.org/abs/2406.09246',
    pdfUrl: 'https://arxiv.org/pdf/2406.09246',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: 'https://github.com/openvla/openvla',
    areaIds: ['area-vla', 'area-foundation'],
    readingStatus: 'skimmed',
    methodKeywords: ['VLA', 'open-source', 'robot foundation model'],
    oneSentenceSummary: '开源的VLA模型，提供了训练代码和模型权重，降低了VLA研究门槛。',
    relevanceToMyResearch: '可以作为基线和实验平台，快速验证想法。',
    limitationsOrQuestions: '训练数据量和多样性如何？性能与闭源模型差距多大？',
    judgementLevel: 'useful',
    inspiredIdeaIds: [],
    createdAt: '2026-06-20T09:00:00Z',
    updatedAt: '2026-06-28T11:00:00Z',
  },
  {
    id: 'paper-wm-001',
    title: 'DreamerV3: Mastering Diverse Domains through World Models',
    authors: 'Danijar Hafner, Jurgis Pasukonis, Jimmy Ba, Timothy Lillicrap',
    year: 2023,
    venue: 'ICLR',
    arxivUrl: 'https://arxiv.org/abs/2301.04104',
    pdfUrl: 'https://arxiv.org/pdf/2301.04104',
    htmlUrl: '',
    feishuNoteUrl: 'https://feishu.cn/docx/xxx-dreamerv3',
    codeUrl: 'https://github.com/danijar/dreamerv3',
    areaIds: ['area-world-models', 'area-robot-learning'],
    readingStatus: 'reviewed',
    methodKeywords: ['world model', 'Dreamer', 'model-based RL', 'reinforcement learning'],
    oneSentenceSummary: '统一的世界模型强化学习算法，在多种任务上实现无超参数调优的SOTA性能。',
    relevanceToMyResearch: '世界模型是机器人规划的基础，Dreamer系列是重要参考。',
    limitationsOrQuestions: '像素级世界模型在复杂3D环境的效率问题；长时间预测的准确性下降。',
    judgementLevel: 'idea_source',
    inspiredIdeaIds: [],
    createdAt: '2026-06-10T08:00:00Z',
    updatedAt: '2026-06-25T16:00:00Z',
  },
  {
    id: 'paper-slam-001',
    title: 'ORB-SLAM3: An Accurate Open-Source Library for Visual, Visual-Inertial and Multi-Map SLAM',
    authors: 'Carlos Campos, Richard Elvira, Juan J. Gómez Rodríguez, et al.',
    year: 2021,
    venue: 'TRO',
    arxivUrl: 'https://arxiv.org/abs/2007.11898',
    pdfUrl: 'https://arxiv.org/pdf/2007.11898',
    htmlUrl: '',
    feishuNoteUrl: 'https://feishu.cn/docx/xxx-orbslam3',
    codeUrl: 'https://github.com/UZ-SLAMLab/ORB_SLAM3',
    areaIds: ['area-slam', 'area-vslam', 'area-vio'],
    readingStatus: 'deep_reading',
    methodKeywords: ['ORB-SLAM', 'visual SLAM', 'VIO', 'multi-map'],
    oneSentenceSummary: '成熟的特征点法视觉/视觉惯性SLAM系统，支持多地图、IMU紧耦合，是VIO基线参考。',
    relevanceToMyResearch: 'VIO方向的经典工作，需要深入理解其IMU预积分和优化框架。',
    limitationsOrQuestions: '弱纹理环境下特征点不足；动态物体影响大；回环检测依赖词袋模型。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: ['idea-vio-dynamic'],
    createdAt: '2026-05-20T10:00:00Z',
    updatedAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'paper-vio-001',
    title: 'VINS-Mono: A Robust and Versatile Monocular Visual-Inertial State Estimator',
    authors: 'Tong Qin, Peiliang Li, Shaojie Shen',
    year: 2018,
    venue: 'TRO',
    arxivUrl: 'https://arxiv.org/abs/1708.03852',
    pdfUrl: 'https://arxiv.org/pdf/1708.03852',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: 'https://github.com/HKUST-Aerial-Robotics/VINS-Mono',
    areaIds: ['area-vio', 'area-state-estimation'],
    readingStatus: 'reviewed',
    methodKeywords: ['VIO', 'VINS-Mono', 'optimization', 'sliding window'],
    oneSentenceSummary: '基于滑动窗口优化的单目VIO经典工作，包含初始化、外参标定、回环检测完整模块。',
    relevanceToMyResearch: 'VIO方向的必读经典，优化框架的重要参考。',
    limitationsOrQuestions: '计算量较大；对初始化质量敏感；动态场景下鲁棒性不足。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: [],
    createdAt: '2026-05-15T09:00:00Z',
    updatedAt: '2026-06-20T14:00:00Z',
  },
  {
    id: 'paper-msf-001',
    title: 'FAST-LIO2: Fast Direct LiDAR-Inertial Odometry',
    authors: 'Wei Xu, Yixi Cai, Dongjiao He, Jiarong Lin, Fu Zhang',
    year: 2022,
    venue: 'TRO',
    arxivUrl: 'https://arxiv.org/abs/2107.06829',
    pdfUrl: 'https://arxiv.org/pdf/2107.06829',
    htmlUrl: '',
    feishuNoteUrl: 'https://feishu.cn/docx/xxx-fastlio2',
    codeUrl: 'https://github.com/hku-mars/FAST_LIO',
    areaIds: ['area-msf', 'area-slam', 'area-state-estimation'],
    readingStatus: 'deep_reading',
    methodKeywords: ['LiDAR SLAM', 'LIO', 'ikd-tree', 'incremental mapping'],
    oneSentenceSummary: '基于ikd-tree的紧耦合激光惯性里程计，实现了高效率、高精度的建图与定位。',
    relevanceToMyResearch: '多传感器融合方向的重要工作，ikd-tree数据结构有参考价值。',
    limitationsOrQuestions: '依赖高频率IMU；对运动畸变敏感；回环检测需额外模块。',
    judgementLevel: 'useful',
    inspiredIdeaIds: [],
    createdAt: '2026-06-05T08:00:00Z',
    updatedAt: '2026-06-30T09:00:00Z',
  },
  {
    id: 'paper-diffusion-001',
    title: 'Diffusion Policy: Visuomotor Policy Learning via Action Diffusion',
    authors: 'Cheng Chi, Siyuan Feng, Yilun Du, et al.',
    year: 2023,
    venue: 'RSS',
    arxivUrl: 'https://arxiv.org/abs/2303.04137',
    pdfUrl: 'https://arxiv.org/pdf/2303.04137',
    htmlUrl: '',
    feishuNoteUrl: '',
    codeUrl: 'https://github.com/columbia-ai-robotics/diffusion_policy',
    areaIds: ['area-diffusion-policy', 'area-robot-learning'],
    readingStatus: 'skimmed',
    methodKeywords: ['diffusion model', 'policy learning', 'visuomotor', 'manipulation'],
    oneSentenceSummary: '用扩散模型生成动作序列，在多模态动作分布建模上优于GMM和BC。',
    relevanceToMyResearch: '扩散策略是机器人学习的新兴方向，值得关注。',
    limitationsOrQuestions: '推理速度慢，难以满足实时控制要求；扩散步数与性能的权衡。',
    judgementLevel: 'idea_source',
    inspiredIdeaIds: ['idea-diffusion-fast'],
    createdAt: '2026-06-22T10:00:00Z',
    updatedAt: '2026-07-02T16:00:00Z',
  },
  {
    id: 'paper-se-001',
    title: 'Quaternion Kinematics for the Error-State Kalman Filter',
    authors: 'Joan Solà',
    year: 2017,
    venue: 'arXiv',
    arxivUrl: 'https://arxiv.org/abs/1110.2165',
    pdfUrl: 'https://arxiv.org/pdf/1110.2165',
    htmlUrl: '',
    feishuNoteUrl: 'https://feishu.cn/docx/xxx-quat-ekf',
    codeUrl: '',
    areaIds: ['area-state-estimation'],
    readingStatus: 'reviewed',
    methodKeywords: ['Kalman filter', 'quaternion', 'error state', 'ESKF'],
    oneSentenceSummary: '误差状态卡尔曼滤波器的四元数运动学推导，是状态估计的理论基础。',
    relevanceToMyResearch: '状态估计的理论基础，必须掌握的经典工作。',
    limitationsOrQuestions: '理论性强，需要结合实践理解；未涉及传感器融合细节。',
    judgementLevel: 'must_review',
    inspiredIdeaIds: [],
    createdAt: '2026-05-10T08:00:00Z',
    updatedAt: '2026-06-15T12:00:00Z',
  },
];

export const mockObservations: Observation[] = [
  {
    id: 'obs-001',
    content: '对比学习论文假设类别分布均衡，但在长尾场景下这个假设不成立',
    type: 'paper',
    keywords: ['对比学习', '长尾分布', '分布假设'],
    potentialIssue: '长尾场景下对比学习的有效性',
    researchValue: 'high',
    researchValueReason: '这是一个基础假设的漏洞，如果成立可能影响广泛',
    suggestedAction: '搜索长尾+对比学习的相关工作',
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'obs-002',
    content: '复现时发现模型在类别 45 上准确率只有 12%，远低于论文报告的 67%',
    type: 'experiment',
    keywords: ['复现失败', '长尾类别', '性能差异'],
    potentialIssue: '报告指标是否选择性展示',
    researchValue: 'medium',
    researchValueReason: '可能是复现问题也可能是真实问题',
    suggestedAction: '检查代码，如果确认不是 bug 则值得深挖',
    createdAt: '2026-07-01T14:30:00Z',
  },
  {
    id: 'obs-003',
    content: '师兄说这个领域大家都在做损失函数改进，数据层面的工作几乎没人做',
    type: 'discussion',
    keywords: ['方法分布', '损失函数', '数据增强'],
    potentialIssue: '为什么数据层面被忽视？是被证明无效还是没人尝试？',
    researchValue: 'high',
    researchValueReason: '如果真没人做，可能是差异化切入点',
    suggestedAction: '搜索数据增强+长尾识别的工作',
    createdAt: '2026-07-02T09:00:00Z',
  },
];

export const mockIdeaCards: IdeaCard[] = [
  {
    id: 'idea-vla-speedup',
    title: 'VLA推理加速：分层动作解码策略',
    status: 'researching',
    researchQuestion: '能否通过分层动作解码，在保持VLA泛化能力的同时大幅提升推理速度？',
    coreHypothesis: '将VLA动作输出分解为"高层语义动作+低层轨迹生成"两层，高层用大模型推理，低层用轻量模型执行，可以在不损失太多泛化性的情况下实现实时控制。',
    whyItMatters: 'VLA是机器人基础模型的核心方向，但当前推理速度（~3s/step）远不能满足实时控制需求（>10Hz），速度瓶颈严重制约了VLA的实际应用。',
    supportingEvidence: [
      { id: 'ev-1', content: '分层控制在机器人领域已被广泛验证', source: '文献', isAIGenerated: true },
      { id: 'ev-2', content: 'RT-2显示VLA输出低层动作效率低', source: '论文', isAIGenerated: true },
    ],
    opposingEvidence: [
      { id: 'ev-3', content: '分层可能导致语义与动作的鸿沟', source: 'AI推理', isAIGenerated: true },
      { id: 'ev-4', content: '高层规划的错误会向下传播', source: 'AI推理', isAIGenerated: true },
    ],
    missingEvidence: [
      { id: 'ev-5', content: '分层架构在未见任务上的泛化性对比', source: '实验验证', isAIGenerated: true },
      { id: 'ev-6', content: '高层语义动作的表示空间设计', source: '研究问题', isAIGenerated: true },
    ],
    biggestRisks: [
      '分层后泛化能力大幅下降，失去VLA的核心优势',
      '高低层接口设计困难，语义鸿沟问题严重',
      '加速效果不明显（<2x），不足以支撑实时应用',
    ],
    sourceObservations: [],
    sourcePaperIds: ['paper-vla-001'],
    areaIds: ['area-vla', 'area-foundation'],
    roboticsTask: '桌面操作（抓取、放置、推动）',
    datasetOrScenario: 'RT-1 / RT-2 数据集 + 自建真实机器人场景',
    baseline: 'RT-2 端到端 VLA',
    evaluationMetric: '任务成功率 + 推理延迟（ms/step）+ 未见任务泛化率',
    nextAction: '在模拟环境中验证分层架构的可行性（预计 1 周）',
    createdAt: '2026-07-02T14:00:00Z',
    updatedAt: '2026-07-03T09:00:00Z',
  },
  {
    id: 'idea-diffusion-fast',
    title: '快速扩散策略：少步扩散用于实时机器人控制',
    status: 'rough',
    researchQuestion: '能否将扩散步数从50步压缩到5步以内，同时保持策略性能，用于实时机器人控制？',
    coreHypothesis: '通过蒸馏或更好的噪声调度，可以用极少的扩散步数（<5步）达到接近全步数的策略性能，从而满足实时控制要求。',
    whyItMatters: '扩散策略在多模态动作建模上有优势，但推理速度是主要瓶颈。如果能实现少步扩散，将大幅提升扩散策略的实用性。',
    supportingEvidence: [
      { id: 'ev-7', content: '图像领域已有少步扩散的成功案例（如LCM）', source: '文献', isAIGenerated: true },
      { id: 'ev-8', content: 'Diffusion Policy展示了扩散在策略学习中的优势', source: '论文', isAIGenerated: true },
    ],
    opposingEvidence: [
      { id: 'ev-9', content: '动作空间维度高，少步扩散可能质量下降严重', source: 'AI推理', isAIGenerated: true },
    ],
    missingEvidence: [
      { id: 'ev-10', content: '动作空间中少步扩散的性能边界', source: '实验验证', isAIGenerated: true },
    ],
    biggestRisks: [
      '少步扩散后策略性能下降超过10%，得不偿失',
      '蒸馏方法的训练复杂度高，难以复现',
    ],
    sourceObservations: [],
    sourcePaperIds: ['paper-diffusion-001'],
    areaIds: ['area-diffusion-policy', 'area-robot-learning'],
    roboticsTask: '桌面机器人操作任务',
    datasetOrScenario: 'Diffusion Policy 标准测试集（PushT、Kitchen等）',
    baseline: 'Diffusion Policy (50步 DDPM)',
    evaluationMetric: '任务成功率 + 推理时间 + 动作分布多样性',
    nextAction: '在PushT数据集上测试少步扩散的性能变化（预计 3 天）',
    createdAt: '2026-07-02T16:00:00Z',
    updatedAt: '2026-07-02T16:00:00Z',
  },
  {
    id: 'idea-vio-dynamic',
    title: '动态VIO：动态场景下的鲁棒视觉惯性里程计',
    status: 'mve_running',
    researchQuestion: '如何在高动态场景下保持VIO的定位精度和鲁棒性？',
    coreHypothesis: '通过动态物体检测与特征点分类，将动态物体上的特征点排除或降权，可以显著提升动态场景下VIO的定位精度。',
    whyItMatters: '真实环境中大量动态物体（人、车）严重影响VIO性能，但现有方法多假设静态环境，动态场景下漂移严重。',
    supportingEvidence: [
      { id: 'ev-11', content: '动态物体是VIO主要误差源之一', source: '文献', isAIGenerated: true },
      { id: 'ev-12', content: '语义分割可以有效识别动态物体', source: '事实', isAIGenerated: true },
    ],
    opposingEvidence: [
      { id: 'ev-13', content: '语义分割增加计算量，可能降低实时性', source: 'AI推理', isAIGenerated: true },
      { id: 'ev-14', content: '误检静态物体为动态可能丢失有效特征', source: 'AI推理', isAIGenerated: true },
    ],
    missingEvidence: [
      { id: 'ev-15', content: '在真实高动态场景下的定量对比实验', source: '实验验证', isAIGenerated: true },
    ],
    biggestRisks: [
      '动态检测的精度不足以支撑VIO改进',
      '计算开销太大，实时性无法保证',
      '提升幅度有限（<10%），不构成独立贡献',
    ],
    sourceObservations: [],
    sourcePaperIds: ['paper-slam-001', 'paper-vio-001'],
    areaIds: ['area-vio', 'area-slam', 'area-dynamic-scene'],
    roboticsTask: '无人机/移动机器人在动态环境中的定位',
    datasetOrScenario: '自采动态场景数据集 + 部分公开数据集（TUM动态序列）',
    baseline: 'VINS-Mono / ORB-SLAM3 标准版本',
    evaluationMetric: 'ATE（绝对轨迹误差）+ 定位失败率 + 处理帧率',
    nextAction: '在TUM动态序列上验证MVE（预计 2 天）',
    createdAt: '2026-06-25T10:00:00Z',
    updatedAt: '2026-07-01T14:00:00Z',
  },
];

export const mockMVEs: MVE[] = [
  {
    id: 'mve-vio-dynamic-001',
    ideaCardId: 'idea-vio-dynamic',
    experimentGoal: '验证动态特征点排除能否在高动态场景下提升VIO定位精度',
    minimalDesign: '在VINS-Mono基础上加入基于语义分割的动态特征点过滤，在TUM动态序列上对比ATE',
    keyVariables: {
      independent: '动态特征处理方式（无处理 / 直接排除 / 降权）',
      dependent: 'ATE绝对轨迹误差 + 定位失败率',
    },
    controlGroups: [
      'Baseline: VINS-Mono 原版（无动态处理）',
      'Proposed: 语义分割+动态特征排除',
      'Ablation: 动态特征降权（不排除）',
    ],
    expectedOutcome: '动态场景下ATE降低30%以上，静态场景下性能不下降',
    failureSignals: [
      'ATE降低幅度<10%',
      '静态场景下ATE反而上升',
      '处理帧率<10Hz，不满足实时要求',
    ],
    minimalEffort: '基于VINS-Mono修改约200行代码，集成轻量语义分割模型，在TUM数据集测试',
    nextTasks: {
      onPass: '扩展到更多动态场景，设计更精细的动态特征处理策略',
      onFail: '考虑其他动态鲁棒VIO方案（如多几何约束）',
    },
    roboticsTask: '移动机器人在动态环境中的定位',
    datasetOrScenario: 'TUM RGB-D Dataset 动态序列（walking/running）',
    baseline: 'VINS-Mono 标准版本',
    evaluationMetric: 'ATE RMSE + 定位失败率 + 处理帧率',
    minimalComputeNeed: '单台带GPU的工作站，推理~20ms/帧',
    expectedTimeCost: '2-3天（代码修改 + 实验运行）',
    resultStatus: 'pending',
    resultNotes: '',
    createdAt: '2026-07-01T14:00:00Z',
  },
];
