export interface ResearchQuestion {
  id: string;
  areaId: string;
  areaName: string;
  text: string;
  type: 'hot' | 'gap' | 'emerging' | 'classic';
  relatedPapers?: string[];
  relatedIdeas?: string[];
  difficulty: 1 | 2 | 3;
  impact: 1 | 2 | 3;
}

export interface QuestionCluster {
  id: string;
  areaId: string;
  title: string;
  description: string;
  questions: string[];
}

export const researchQuestions: ResearchQuestion[] = [
  {
    id: 'vla-1',
    areaId: 'area-vla',
    areaName: 'VLA｜视觉语言动作模型',
    text: '如何让 VLA 在完全未见的机器人形态上实现 zero-shot 迁移？',
    type: 'gap',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'vla-2',
    areaId: 'area-vla',
    areaName: 'VLA｜视觉语言动作模型',
    text: 'VLA 的推理速度如何提升到实时控制（>30Hz）？',
    type: 'hot',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'vla-3',
    areaId: 'area-vla',
    areaName: 'VLA｜视觉语言动作模型',
    text: '如何在保证语义泛化的同时减小 VLA 模型规模？',
    type: 'hot',
    difficulty: 2,
    impact: 3,
  },
  {
    id: 'vla-4',
    areaId: 'area-vla',
    areaName: 'VLA｜视觉语言动作模型',
    text: 'VLA 的 safety constraint 如何有效融入训练和推理？',
    type: 'emerging',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'vla-5',
    areaId: 'area-vla',
    areaName: 'VLA｜视觉语言动作模型',
    text: '多模态动作分布（如 diffusion/flow matching）如何与 VLM 更好结合？',
    type: 'emerging',
    difficulty: 3,
    impact: 2,
  },
  {
    id: 'slam-1',
    areaId: 'area-slam',
    areaName: 'SLAM｜同步定位与建图',
    text: '动态环境下 SLAM 如何保持长期鲁棒性？',
    type: 'classic',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'slam-2',
    areaId: 'area-slam',
    areaName: 'SLAM｜同步定位与建图',
    text: '如何实现跨传感器模态的通用 SLAM 框架？',
    type: 'gap',
    difficulty: 3,
    impact: 2,
  },
  {
    id: 'slam-3',
    areaId: 'area-slam',
    areaName: 'SLAM｜同步定位与建图',
    text: '大模型如何提升 SLAM 的语义理解和决策能力？',
    type: 'emerging',
    difficulty: 2,
    impact: 3,
  },
  {
    id: 'diffusion-1',
    areaId: 'area-diffusion',
    areaName: 'Diffusion Policy｜扩散策略',
    text: 'Diffusion Policy 的推理速度如何从秒级提升到毫秒级？',
    type: 'hot',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'diffusion-2',
    areaId: 'area-diffusion',
    areaName: 'Diffusion Policy｜扩散策略',
    text: '如何将 Diffusion Policy 扩展到 long-horizon 任务？',
    type: 'gap',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'diffusion-3',
    areaId: 'area-diffusion',
    areaName: 'Diffusion Policy｜扩散策略',
    text: 'Flow matching vs Diffusion 在机器人控制中的本质差异是什么？',
    type: 'hot',
    difficulty: 2,
    impact: 2,
  },
  {
    id: 'worldmodel-1',
    areaId: 'area-world-model',
    areaName: 'World Model｜世界模型',
    text: '如何构建可迁移到真实世界的通用世界模型？',
    type: 'gap',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'worldmodel-2',
    areaId: 'area-world-model',
    areaName: 'World Model｜世界模型',
    text: '世界模型的预测精度与计算成本之间的最优权衡是什么？',
    type: 'hot',
    difficulty: 2,
    impact: 3,
  },
  {
    id: 'worldmodel-3',
    areaId: 'area-world-model',
    areaName: 'World Model｜世界模型',
    text: '如何让世界模型学会物理规则而非仅仅拟合数据？',
    type: 'emerging',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'rl-1',
    areaId: 'area-rl',
    areaName: 'Reinforcement Learning｜强化学习',
    text: '如何大幅降低机器人 RL 的样本复杂度？',
    type: 'classic',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'rl-2',
    areaId: 'area-rl',
    areaName: 'Reinforcement Learning｜强化学习',
    text: 'RL 与 VLA 如何有效结合实现 online improvement？',
    type: 'emerging',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'rl-3',
    areaId: 'area-rl',
    areaName: 'Reinforcement Learning｜强化学习',
    text: '如何在安全约束下进行高效的机器人 RL？',
    type: 'hot',
    difficulty: 3,
    impact: 2,
  },
  {
    id: 'embodied-1',
    areaId: 'area-embodied',
    areaName: 'Embodied AI｜具身智能',
    text: '具身智能的"具身"到底体现在哪些方面？',
    type: 'emerging',
    difficulty: 2,
    impact: 3,
  },
  {
    id: 'embodied-2',
    areaId: 'area-embodied',
    areaName: 'Embodied AI｜具身智能',
    text: '如何让具身智能体在开放世界中持续学习？',
    type: 'gap',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'embodied-3',
    areaId: 'area-embodied',
    areaName: 'Embodied AI｜具身智能',
    text: '语言理解与具身交互的最优接口是什么？',
    type: 'hot',
    difficulty: 2,
    impact: 3,
  },
  {
    id: 'foundation-1',
    areaId: 'area-foundation',
    areaName: 'Robotics Foundation Models｜机器人基础模型',
    text: '机器人基础模型应该具备哪些核心能力？',
    type: 'emerging',
    difficulty: 2,
    impact: 3,
  },
  {
    id: 'foundation-2',
    areaId: 'area-foundation',
    areaName: 'Robotics Foundation Models｜机器人基础模型',
    text: '如何评估机器人基础模型的通用性？',
    type: 'gap',
    difficulty: 2,
    impact: 2,
  },
  {
    id: 'foundation-3',
    areaId: 'area-foundation',
    areaName: 'Robotics Foundation Models｜机器人基础模型',
    text: '机器人基础模型的 scaling law 是什么？',
    type: 'hot',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'control-1',
    areaId: 'area-control',
    areaName: 'Robot Control｜机器人控制',
    text: '如何实现自适应、鲁棒的通用机器人控制器？',
    type: 'classic',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'control-2',
    areaId: 'area-control',
    areaName: 'Robot Control｜机器人控制',
    text: '学习控制器与传统控制器如何有效融合？',
    type: 'hot',
    difficulty: 2,
    impact: 2,
  },
  {
    id: 'control-3',
    areaId: 'area-control',
    areaName: 'Robot Control｜机器人控制',
    text: '大模型如何提升控制器的高层决策能力？',
    type: 'emerging',
    difficulty: 2,
    impact: 3,
  },
  {
    id: 'perception-1',
    areaId: 'area-perception',
    areaName: 'Robot Perception｜机器人感知',
    text: '如何实现端到端的多模态感知融合？',
    type: 'hot',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'perception-2',
    areaId: 'area-perception',
    areaName: 'Robot Perception｜机器人感知',
    text: '感知系统如何处理传感器故障和退化？',
    type: 'gap',
    difficulty: 2,
    impact: 2,
  },
  {
    id: 'perception-3',
    areaId: 'area-perception',
    areaName: 'Robot Perception｜机器人感知',
    text: '大模型如何提升感知的语义理解能力？',
    type: 'emerging',
    difficulty: 2,
    impact: 3,
  },
  {
    id: 'sim2real-1',
    areaId: 'area-sim2real',
    areaName: 'Sim-to-Real｜仿真到真实',
    text: '如何系统性地缩小 sim-to-real gap？',
    type: 'classic',
    difficulty: 3,
    impact: 3,
  },
  {
    id: 'sim2real-1',
    areaId: 'area-sim2real',
    areaName: 'Sim-to-Real｜仿真到真实',
    text: '如何构建能够迁移到真实世界的仿真环境？',
    type: 'hot',
    difficulty: 3,
    impact: 3,
  },
];

export const questionClusters: QuestionCluster[] = [
  {
    id: 'cluster-vla-cross',
    areaId: 'area-vla',
    title: '跨形态泛化',
    description: 'VLA 在不同机器人形态之间的迁移能力',
    questions: ['vla-1'],
  },
  {
    id: 'cluster-vla-speed',
    areaId: 'area-vla',
    title: '推理速度',
    description: 'VLA 推理速度优化与实时控制',
    questions: ['vla-2'],
  },
  {
    id: 'cluster-vla-size',
    areaId: 'area-vla',
    title: '模型规模',
    description: 'VLA 模型压缩与效率优化',
    questions: ['vla-3'],
  },
  {
    id: 'cluster-slam-dynamic',
    areaId: 'area-slam',
    title: '动态环境鲁棒性',
    description: 'SLAM 在动态场景中的挑战',
    questions: ['slam-1'],
  },
  {
    id: 'cluster-diffusion-speed',
    areaId: 'area-diffusion',
    title: '推理加速',
    description: 'Diffusion Policy 的推理效率优化',
    questions: ['diffusion-1'],
  },
  {
    id: 'cluster-diffusion-long',
    areaId: 'area-diffusion',
    title: '长时序任务',
    description: 'Diffusion Policy 在 long-horizon 任务中的应用',
    questions: ['diffusion-2'],
  },
  {
    id: 'cluster-worldmodel-transfer',
    areaId: 'area-world-model',
    title: '真实迁移',
    description: '世界模型从仿真到真实的迁移',
    questions: ['worldmodel-1'],
  },
  {
    id: 'cluster-embodied-learning',
    areaId: 'area-embodied',
    title: '持续学习',
    description: '具身智能体的终身学习能力',
    questions: ['embodied-2'],
  },
];

export const QUESTION_TYPE_LABELS: Record<ResearchQuestion['type'], { label: string; color: string; bgColor: string }> = {
  hot: { label: '热门', color: 'text-red-600', bgColor: 'bg-red-50' },
  gap: { label: '空白', color: 'text-blue-600', bgColor: 'bg-blue-50' },
  emerging: { label: '新兴', color: 'text-green-600', bgColor: 'bg-green-50' },
  classic: { label: '经典', color: 'text-purple-600', bgColor: 'bg-purple-50' },
};

export const DIFFICULTY_LABELS: Record<number, { label: string; color: string }> = {
  1: { label: '入门', color: 'text-green-600' },
  2: { label: '进阶', color: 'text-amber-600' },
  3: { label: '挑战', color: 'text-red-600' },
};

export const IMPACT_LABELS: Record<number, { label: string; color: string }> = {
  1: { label: '局部', color: 'text-muted' },
  2: { label: '领域', color: 'text-accent' },
  3: { label: '跨领域', color: 'text-accent2' },
};
